###################################################################################################
#
# str_pt.pm
#
###################################################################################################

use strict;

###################################################################################################

sub load_str
{
  return (

	######## common.pm ########

	'MENU'					=> 'Menu',
	'SUBMENU'				=> 'Sub Menu',
	'BACK'					=> 'Voltar',
	'NOW_EXCEL_IS_BOOTING'			=> 'Excel esta inicializando ...',
	'NO_DATA_FOUND'				=> 'Nenhum dado encontrado',
	'NO_DATA_FOUND_IN_THIS_CONDITION'	=> 'Nenhum dado encontrado nestas condicoes.',

	######## Main Menu ########

	'MAIN_MENU'			=> 'Menu Principal',
	'SHIFT_REPORT'			=> 'Relatorio de Turno',
	'OPERATOR_REPORT'		=> 'Relatorio por Operador',
	'STYLE_REPORT'			=> 'Relatorio de Artigo',
	'PRODUCTION_GRAPH'		=> 'Grafico de Producao',
	'EFFICIENCY_GRAPH'		=> 'Grafico de Eficiencia',
	'STATUS_HISTORY'		=> 'Historico',
	'STOP_ANALYSIS_GRAPH'		=> 'Grafico de Analise de Paradas',
	'YARN_INVENTORY_FORECAST'	=> 'Inventario de Fio e Previsao',
	'STOP_HISTORY'			=> 'Historico de Parada',
	'DATA_COLLECTION_NETWORK'	=> 'Coleta de Dados(Rede)',
	'DATA_IMPORT_MEMCARD'		=> 'Importar Dados(Cartao de Memoria)',
	'LINK_TO_LOOM_SCREEN'		=> 'Link para Tela da Maquina',
	'REPORT_SETTING'		=> 'Ajuste de Relatorio',
	'IP_ADDRESS_SETTING'		=> 'Ajuste de Endereco IP',
	'PASSWORD_SETTING'		=> 'Ajuste de Senha',
	'SHIFT_DATA'			=> 'Dados do Turno',
	'OPERATOR_DATA'			=> 'Dados do Operador',
	'LOOM_DATA'			=> 'Dados do Tear',
	'SETTING'			=> 'Ajuste',
	'DATA_EDIT'			=> 'Editar Dados',
	'DATA_EDIT_MENU'		=> 'Editar Dados Sub Menu',
	'EXPORT_CSV_FILE'		=> 'Exportar arquivo CSV',

	######## Shift data & Operator data ########

	'SELECT_BY_LOOM'		=> 'Selecionar por Tear',
	'SELECT_BY_STYLE'		=> 'Selecionar por Artigo',
	'OPERATOR'			=> 'Operador',
	'PERIOD'			=> 'Periodo',
	'SELECT_ALL'			=> 'Selecionar Todos',
	'SHOW_GRAPH'			=> 'Mostrar Grafico',
	'SHOW_REPORT'			=> 'Mostrar Relatorio',

	######## Setting ########

	'RESET_MODEIFY'				=> 'Ajustar Modificacao',
	'ENTER'					=> 'ENTER',
	'PLEASE_CHECK_COLOR_NUM'		=> 'Verificar numero da cor',
	'PLEASE_INPUT_NUMBER'			=> 'Inserir numero',
	'IP_NUMBER_MUST_BE_BETWEEN_0_AND_255'	=> 'O numero de IP deve estar entre 0 e 255.',
	'DELETE'				=> 'Deletar',
	'RANGE_OF_IP_ADDRESS'			=> 'Faixa de endereço IP',
	'SETTING_RESULT'			=> 'Resultado do Ajuste',
	'SETTING_SUCCEED'			=> 'Ajustado com sucesso.',
	'NO_VALID_DATA_FOUND'			=> 'Nenhum dado valido encontrado.',
	'APPLY_CHANGE_TO_DATA'			=> 'Aplicar alteracao aos dados',
	'OK'					=> 'OK',

	'PASSWORD_IS_TOO_SHORT'		=> 'Senha e muito curta.',
	'NEED_6_CHARACTERS_OR_MORE'	=> 'Necessidade de 6 caracteres ou mais.',
	'CANT_USE_SPACE_FOR_PASSWORD'	=> "Nao e possivel usar ESPACO para senha.",
	'THE_PASSWORDS_DO_NOT_MATCH'	=> 'As senhas nao coincidem.',
	'DISABLE_PASSWORD'		=> 'Desativar senha',
	'ENABLE_PASSWORD'		=> 'Habilitar senha',
	'USERNAME'			=> 'Usuario',
	'NEW_PASSWORD'			=> 'Nova senha',
	'CONFIRM_NEW_PASSWORD'		=> 'Confirmar nova senha',
	'PASSWORD_ERROR'		=> 'Erro de senha.',
	'PASSWORD_TARGET_AREA'		=> 'Area de senha',

	'PICK'				=> 'batida',
	'METER'				=> 'metro',
	'YARD'				=> 'jarda',

	'WARP_TOP_MISS'			=> 'Urdume(Superior)',
	'WARP_MISS'			=> 'Urdume',
	'FALSE_SELVAGE_MISS'		=> 'Ourela Falsa',
	'LENO_L_MISS'			=> 'Giro(Esq)',
	'LENO_R_MISS'			=> 'Giro(Dir)',
	'WEFT_MISS'			=> 'Trama',
	'WARP_OUT'			=> 'Troca de rolo de urdume',
	'CLOTH_DOFFING'			=> 'Troca de rolo de tecido',
	'MANUAL_STOP'			=> 'Manual',
	'POWER_OFF'			=> 'Desligada',
	'OTHER_STOP'			=> 'Outro',

	'WF1'				=> 'WF1',
	'WF2'				=> 'WF2',
	'LH'				=> 'LH',

	'COLOR1'			=> 'Cor1',
	'COLOR2'			=> 'Cor2',
	'COLOR3'			=> 'Cor3',
	'COLOR4'			=> 'Cor4',
	'COLOR5'			=> 'Cor5',
	'COLOR6'			=> 'Cor6',

	'STOP_CAUSE'			=> 'Causa de Parada',
#	'DETAIL_OF_WEFT_STOP'		=> 'Detalhes de Parada de Trama',
	'UNIT'				=> 'Unidade',
	'START_OF_WEEK'			=> 'Inicio da Semana',
	'CONDITION_OF_TOTALING'		=> 'Condicao de Totalizacao',

	'BEAM_TYPE'			=> 'Tipo de Rolo de Urdume',
	'SINGLE_BEAM'			=> 'Rolo simples',
	'DOUBLE_BEAM'			=> 'Rolo duplo',

	'SHIFT'				=> 'Turno',
	'DATE'				=> 'Data',
	'WEEK'				=> 'Semana',
	'MONTH'				=> 'Mes',

	'SUNDAY'			=> 'Dom.',
	'MONDAY'			=> 'Seg.',
	'TUESDAY'			=> 'Ter.',
	'WEDNESDAY'			=> 'Qua.',
	'THURSDAY'			=> 'Qui.',
	'FRIDAY'			=> 'Sex.',
	'SATDAY'			=> 'Sab.',

	'EFFICIENCY'			=> 'Eficiencia',
	'RUN_TIME'			=> 'Tempo em Operacao',
	'PERCENT_OVER'			=> '% Excedente',
	'MINUITE_OVER'			=> 'Min. Excedente',

	'REPORT_ITEM'			=> 'Item do Relatorio',
	'TOP_BEAM_NAME'			=> 'Nome do Rolo Superior',
	'BEAM_NAME'			=> 'Nome do Rolo de Urdume',
	'RPM'				=> 'RPM',
	'STOP_TIME'			=> 'Tempo Parada',
	'PRODUCTION'			=> 'Producao',

	'PERMISSION_DENY'				=> 'Permissao Negada',
	'CANT_ACCESS_THIS_PAGE_FROM_REMOTE'		=> "Nao e possivel acessar esta pagina remotamente.",
	'DISABLE_PASSWORD_FORCIBLY'			=> 'Desabilitar senha forcadamente',
	'ARE_YOU_SURE_YOU_WANT_TO_DISABLE_PASSWORD'	=> 'Tem certeza de que deseja desabilitar a senha?',
	'PASSWORD_IS_DISABLED'				=> 'Senha esta desativada.',

	'LANGUAGE_SETTING'		=> 'Ajuste de Idioma',

	######## Loom data ########

	'CANCEL_DATA_COLLECTING'	=> 'Cancelar Coleta de Dados',
	'CLOSE'				=> 'Fechar',
	'DATA_COLLECTING_IS_CANCELED'	=> 'Coleta de Dados Cancelada.',
	'SUCCEED'			=> 'Com Sucesso',
	'START_DATA_COLLECTING'		=> 'Iniciar Coleta de Dados',
	'END_DATA_COLLECTING'		=> 'Finalizar Coleta de Dados',
	'NO_DATA_COLLECTED'		=> 'Nenhum Dado Coletado',
	'START_DATA_CONVERTING'		=> 'Iniciar Conversao de Dados',
	'COMPLETED_ALL_PROPERLY'	=> 'Completado Normalmente',
	'PHASE'				=> 'Fase',
	'DONE'				=> 'Concluido',
	'LOOM_CLOCK_IS_WRONG'		=> 'Horario do Tear Incorreto',

	'LOOM_CLOCK_SETTING'			=> 'Ajuste do Horario do Tear',
	'TARGET_DATE'				=> 'Data',
	'CANCEL_LOOM_CLOCK_SETTING'		=> 'Cancelar Ajuste de Horario do Tear',
	'START_LOOM_CLOCK_SETTING'		=> 'Iniciar Ajuste de Horario do Tear',
	'LOOM_CLOCK_SETTING_IS_CANCELED'	=> 'Ajuste de Horario do Tear Cancelado',
	'END_LOOM_CLOCK_SETTING'		=> 'Finalizar Ajuste de Horario do Tear',
	'SET_CLOCK'				=> 'Horario Ajustado',
	'NOT_NEED_ADJUST'			=> 'Ajuste nao necessario',
	'TIME_DIFFERENCE'			=> 'Diferenca de Horario',

	'SEC'		=> 'seg',
	'MINUITE'	=> 'min',
	'HOUR'		=> 'hora',
	'DAY'		=> 'dia',
	'YEAR'		=> 'ano',

#	'PARENT_FOLDER'			=> 'Pasta Principal',
#	'BACK_TO_PREV_FOLDER'		=> 'Voltar a pasta anterior',
	'CANNOT_ACCESS_THIS_FOLDER'	=> "Nao e possivel acessar esta pasta",
	'CANNOT_FIND_THIS_FOLDER'	=> "Nao e possivel encontrar pasta",
	'NO_FILES'			=> "Nenhum arquivo",
#	'NO_SUB_FOLDERS'		=> "Nenhuma sub pasta",
	'CURRENT_FOLDER'		=> 'Pasta atual',
#	'MOVE_TO_SUB_FOLDER'		=> 'Mover para sub pasta',
#	'MOVE_TO_THIS_FOLDER'		=> 'Mover para esta pasta',
#	'SUB_FOLDER_LIST'		=> 'Lista sub pastas',
	'FILE_LIST'			=> 'Lista de arquivos',
	'IMPORT_SELECTED_FILES'		=> 'Importar pastas selecionadas',

	'START_DATA_CHECKING'		=> 'Iniciar verificacao de dados',
	'FUTURE_DATA' 			=> 'Dado futuro',
	'TOO_OLD_DATA'			=> 'Dados muito antigos',
	'CANT_READ_FILE'		=> "Nao e possivel ler o arquivo",
	'DATA_ERROR'			=> 'Dado inapropriado',
	'NOT_TMS_DATA'			=> 'Nao e dado do TMS',
	'THERE_IS_NO_VALID_DATA'	=> 'Dados invalidos',

	'SHOW_STYLE_LIST'		=> 'Mostrar Historico de Artigos',
	'STYLE_NAME'			=> 'Nome do Artigo',
	'SET_STYLE'			=> 'Ajustar Nome do Artigo',
	'LOOM_NAME'			=> 'Nome do Tear',
	'CURRENT_LOOM_NAME'		=> 'Nome do Tear Atual',
	'NEW_LOOM_NAME'			=> 'Novo Nome do Tear',
	'CHANGE_LOOM_NAME'		=> 'Substituir Nome do Tear',
	'CHANGE_SELECT_LOOM_NAME_OK'	=> 'Tem certeza de que deseja substutir Nome do Tear?',
	'CHANGEING_DATA'		=> 'Substituicao de dados',
	'DELETE_DATA'			=> 'Deletar Dados',
	'DELETE_SELECT_DATA_OK'		=> 'Tem certeza de que deseja deletar dados?',
	'DELETING_DATA'			=> 'Deletando Dados',
	'SELECT_EXPORT_DATA'		=> 'Selecionar Dados para Exportar',
	'EXPORT_DATA'			=> 'Exportar Dados',
	'EXPORT_DONE'			=> 'Exportacao Concluida',
	'SAVE_FOLDER'			=> 'Pasta Salva',
	'REPORT_DATA_RESTRUCTION'	=> 'Relatorio Reestruturacao de Dados',

	'DATA_IS_UNDER_UPDATING'	=> 'Dados estao sendo atualizados',
	'OPERATION_OVERLAPED'		=> 'Interferencia na Operacao',
	'BE_IN_USE_BY_OTHER_USER'	=> 'Outro usuario executando esta operacao',
	'TRY_AGAIN_AFTER_A_WHILE'	=> 'Tente novamente mais tarde',
	'USING_USER'			=> 'Executando Usuario',
	'LOCAL_USER'			=> 'Usuario Local',
	'REMOTE_USER'			=> 'Usuario Remoto',

	'NOT_RESTRUCTION'		=> 'Dados nao estao reestruturados',
	'NEED_RESTRUCTION_FIRST'	=> 'E necessario reestruturar primeiro',
	'KEEP_GOING'			=> 'Continuar',

	######## IP Table ########

	'CANCEL_PROCESSING'		=> 'Cancelar Processamento',
	'NO_NAME'			=> 'Nenhum Nome',
	'NO_LOOM_SELECTED'		=> 'Nenhum Tear Selecionado',

	'CREATE_IP_TABLE'		=> 'Criar Tabela de IP',
	'IPTABLE_INPUT_IP_MSG'		=> 'Inserir inicio e fim do endereco de IP das maquinas',
	'IPTABLE_INPUT_NAME_MSG'	=> 'Inserir Nomes das Maquinas',
	'IPTABLE_SELECT_ITEM_MSG'	=> 'Selecionar itens para adicionar ao MENU',
	'IPTABLE_DATA_CONFIRM_MSG'	=> 'MENU construido sob seguintes condicoes',
	'IPTABLE_DUPLICATE_MSG'		=> 'Duplicar dados encontrados nestes grupos',
	'PLEASE_INPUT_0_255_NUMBER'	=> 'Inserir numeros 0-255.',
	'PLEASE_INPUT_000_999_NUMBER'	=> 'Inserir numeros 000-999.',
	'PLEASE_INPUT_IP_ADDRESS'	=> 'Inserir endereco IP.',
	'GROUP'				=> 'Grupo',
	'DOWNLOAD_IP_TABLE_DATA'	=> 'Baixar Dados Tabela IP',

	'STYLE_MANAGER'			=> 'Gerenciador de Artigos',
	'PATTERN_MANAGER'		=> 'Gerenciador de Padrao',
	'PARTS_CATALOG'			=> 'Catalogo de Pecas',
	'EFFICIENCY_BOARD'		=> 'Quadro de Eficiencia',
	'WEB_CAMERA'			=> 'Web camera',

	'PAGE_1'			=> 'PAG 1',
	'PAGE_2'			=> 'PAG 2',
	'PAGE_3'			=> 'PAG 3',
	'NEXT'				=> 'PROXIMO',
	'CREATE_FILE'			=> 'CRIAR ARQUIVO',
	'DOWNLOAD_FILE'			=> 'BAIXAR ARQUIVO',

	'SEND_IP_TABLE_TO_MACHINES'	=> 'Enviar Tabela IP para Maquinas',
	'CANCEL_SEND_DATA'		=> 'Cancelar Envio de Dados',
	'START_SEND_DATA'		=> 'Iniciar Envio de Dados',
	'SEND_DATA_IS_CANCELED'		=> 'Envio de Dados Cancelado',
	'END_SEND_DATA'			=> 'Finalizar Envio de Dados',

	'IP_TABLE_VERSION_CHECK'	=> 'Verificacao Tabela de IP',
	'CANCEL_VERSION_CHECK'		=> 'Cancelar Verificacao',
	'START_VERSION_CHECK'		=> 'Iniciar verificacao',
	'VERSION_CHECK_IS_CANCELED'	=> 'Verificacao Cancelada',
	'END_VERSION_CHECK'		=> 'Verificacao Finalizada',
	'HOST_IP_TABLE_VERSION'		=> 'Tabela de IP Host',
	'LOOM_IP_TABLE_VERSION'		=> 'Tabela de IP Tear',

	######## For Service TMS ########

	'SERVICE_REPORT'		=> 'Dados Relatorio Servico',
#	'IMPORT_SERVICE_MEMCARD'	=> 'Importar dados (para servico)',
#	'LOG_MESSAGE_TRANSLATION'	=> 'Entrar Traducao Mensagem',
	'SWITCH_USE_DATA'		=> 'Trocar Dado Usado',
	'SWITCH_DATA'			=> 'Trocar Dado',
	'CURRENT_USE_DATA'		=> 'Dado Usado Atual',
	'NOT_EXIST'			=> 'Nao Existe',
	'SELECT_SWITCH_DATA'		=> 'Selecionar Dado de troca',
	'EXEC_SWITCH_DATA'		=> 'Exec Troca',
	'RENAME_DATA'			=> 'Renomear Dados',
	'NEW_NAME'			=> 'Novo Nome',
	'SELECT_RENAME_DATA'		=> 'Selecionar Dado Renomeado',
	'EXEC_RENAME_DATA'		=> 'Exec Renome',
	'CREATE_DATA'			=> 'Criar Nova Area de Dados',
	'CREATE_NAME'			=> 'Novo Nome',
	'EXEC_CREATE_DATA'		=> 'Exec Criacao Dados',
	'SELECT_DELETE_DATA'		=> 'Selecionar Dado Deletado',
	'EXEC_DELETE_DATA'		=> 'Deletar',
	'PLEASE_SELECT_DATA'		=> 'Selecionar Dado.',
	'PLEASE_INPUT_NAME'		=> 'Inserir Nome.',
	'DUPLICATE_NAME'		=> 'Duplicar Nome, Trocar Nome Inserido.',
	'INPUT_DATA_FILE_NAME'		=> 'Inserir Nome Arquivo Dados',

	######## For TMS Scanner ########

	'CLOTH_BEAM_LIST_SETTING'	=> 'Ajuste lista Rolo Tecido',	#1
	'OTHER_LIST_SETTING'		=> 'Ajuste outras listas',
	'CLOTH_BEAM_MAINTENANCE'	=> 'Manutencao Rolo Tecido',
	'SCANNER_SETTING'		=> 'Ajuste Scanner',
	'STYLE_SETTING'			=> 'Ajuste Artigo',
	'SHIFT_SCHEDULE_SETTING'	=> 'Trocar Ajuste Cronograma',
	'UNIT_SETTING'			=> 'Ajuste Unidade',
	'LOOM_NAME_SPEC_SETTING'	=> 'Ajuste Especificacao do Tear',
	'OPERATION_STATUS' 		=> 'Display Operacao',

#	'JAT710_IP_ADDRESS'			=> 'Endereco IP JAT710',	#34
#	'JAT710_MEMORY_CARD'			=> 'Cartao Memoria JAT710',	#35
	'COLLECT_DATA_USING_MEMORY_CARD'	=> 'Coletar Dados Cartao Memoria',	#36
	'SCANNER_IP_ADDRESS'			=> "Endereco IP Scanners",	#37
	'IP_ADDRESS'				=> 'Endereco IP',		#38

	'UPDATE_SETTING'	=> 'Atualizar Ajuste.',	#10

	'INVALID_INPUT_VALUE'	=> 'Valor Inserido esta Incorreto.',	#26
	'ALPHANUMERIC_ONLY'	=> 'Apenas caracteres alfanumerico',	#28
	'UPDATE_OK'		=> 'Atualizacao OK?',		#iTTCS

	'SCANNER'		=> 'Scanner',	#11
	'YES'			=> 'Sim',	#29
	'NO'			=> 'Nao',	#30
	'PAGE'			=> 'Pagina',	#20
	'REFRESH'		=> 'Atualizar display.',	#76

	'LENGTH_UNIT'		=> 'unidade Comprimento',	#52
	'DENSITY_UNIT'		=> 'unidade Densidade',	#53

	'STATUS'		=> 'Status',		#68
	'DURATION'		=> 'Continuando',	#69
	'STOP_COUNT'		=> 'Paradas',		#70
	'EFFICIENCY'		=> 'Eficiencia',		#71
	'CURRENT_SHIFT'		=> 'Turno Atual',		#72
	'DOFFING_FORECAST'	=> 'Previsao Troca Rolo Tecido',	#73
	'WARP_OUT_FORECAST'	=> 'Previsao Troca Urdume',	#74
	'HH_MM'			=> 'Hora:Min',		#75
	'LOWER'			=> 'Inferior',		#55,56,57
	'UPPER'			=> 'Superior',

	'DENSITY'		=> 'Densidade',		#43
	'DOFF_LENGTH'		=> 'Comprimento Troca Rolo',	#44
	'SHRINKAGE'		=> 'Taxa Contracao',		#54
	'UPPER_BEAM'		=> 'Urdume Superior',		#55
	'LOWER_BEAM'		=> 'Urdume Inferior',		#56
	'BEAM'			=> 'Rolo',			#57
	'SET_LENGTH'		=> 'Ajuste Comprimento',		#58
	'USE_EACH_DOFF_LENGTH'	=> 'Ajustar comprimento de troca de rolo individualmente.',	#59
	'CLOTH'			=> 'Tecido',			#60
	'CLOTH_LENGTH'		=> 'Comprimento Tecido',		#61
	'BEAM_REMAIN'		=> 'Comprimento Urdume remanescente',	#62
	'CORRECT_CLOTH_LENGTH'		=> 'Comprimento Tecido Corrigido.',	#63
	'CORRECT_BEAM_REMAIN'		=> 'Comprimento de Urdume no Rolo Corrigido.',	#64
	'FORECAST_EFFICIENCY'		=> 'Taxa de operacao prevista',		#65
	'CLOTH_LENGTH_CORRECTION'	=> 'Coeficiente Correcao Comprimento Tecido',	#66

	'LOOM_ID'		=> 'ID Maquina',	#39
	'SET_TO_ALL'		=> 'Aplicar a todos.',	#40

	'SHIFT_SCHEDULE'	=> 'Trocar Cronograma',	#48
	'SIMPLE_SETTING'	=> 'Ajuste Facil',	#49
	'DETAIL_SETTING'	=> 'Ajuste Detalhado',	#50
	'SHIFT_NUMBER'		=> 'Numero Turnos',	#51

	'OPST__RUN'		=> 'em Operacao',		#77
	'OPST__OUT_OF_PRODUCT'	=> 'Fora de Operacao',
	'OPST__WARP_OUT'	=> 'Troca Urdume',
	'OPST__CLOTH_DOFFING'	=> 'Troca Tecido',
	'OPST__MACHINE_FAILURE'	=> 'Chamada(Maquina)',
	'OPST__CLOTH_MENDING'	=> 'Chamada(Tecido)',
	'OPST__POWER_OFF'	=> 'Desligada',
	'OPST__WARP_TOP'	=> 'Urdume(Superior)',
	'OPST__WARP'		=> 'Urdume',
	'OPST__FALSE_SELVAGE'	=> 'Ourela Falsa',
	'OPST__CC_FRONT'	=> 'Ourela Falsa(Frente)',
	'OPST__CC_REAR'		=> 'Ourela Falsa(Atras)',
	'OPST__LENO_L'		=> 'Giro Ingles(Esq)',
	'OPST__LENO_R'		=> 'Giro Ingles(Dir)',
	'OPST__WEFT'		=> 'Trama',
	'OPST__MANUAL'		=> 'Manual',
	'OPST__OTHER'		=> 'Outro',		#91
	'OPST__COMM_ERR'	=> 'Erro Com',	#92
	'OPST__DATA_ERR'	=> 'Erro DADOS',	#93
	'OPST__NOT_SUPPORT'	=> 'Nao Suporta',	#94

 	'PER_CM'		=> '/cm',
	'PER_INCH'		=> '/polegada',

	'ERROR'			=> 'Erro',	#12
	'DUPLICATE_MAC_NAME'	=> 'Seguintes nomes maquinas estao se sobrepondo.',	#41
	'DUPLICATE_STYLE_NAME'	=> 'Seguintes nomes itens estao se sobrepondo. ',	#46
	'BACK_TO_SETTING'	=> 'Retornar ao display de ajuste',		#32

	'SCANNER_UPLOAD_ERROR'		=> 'Falha ao atualizar o ajuste do scanner.',	#13
	'SCANNER_COMM_ERROR'		=> 'Falha ao comunicar com scanner.',	#14
	'THIS_IP_IS_NOT_SCANNER1'	=> 'O seguinte valor nao e o endereco IP do Scanner 1.',	#15
	'SCANNER_CONFIG_ERROR'		=> 'Scanners nao estao configurados corretamente.',	#16
	'CHECK_SCANNER_CONFIG'		=> 'Verifique o ajuste de cada scanner.',	#17
	'SCANNER_IS_NOT_RUN'		=> 'Scanners nao foram inicializados.',			#19

	######## For LWT ########

	'DETAIL_OF_STOP_CAUSE'	=> 'Detalhes de Causa de Parada',
	'CC_FRONT_MISS'		=> 'Ourela Falsa(Frente)',
	'CC_REAR_MISS'		=> 'Ourela Falsa(Atras)',
	'LENO_MISS'		=> 'Giro Ingles',

	'LOOM_IP_ADDRESS'	=> "Endereco IP Teares",
	'USE_OF_MEMORY_CARD'	=> 'Uso do Cartao de Memoria',

	'OTHER_SETTING'				=> 'Outros Ajustes',
	'DATA_COLLECTION_WARNING_TIME'		=> 'Alarme de tempo de coleta de dados',
	'DATA_IS_NOT_COLLECTED_FOR_A_WHILE'	=> 'Coleta de dados nao realizada ha algum tempo',
	'MOVE_TO_DATA_COLLECTION'		=> 'Mover para Pagina [Coleta de Dados]',
	'IS_DATA_COLLECTED_FIRST'		=> 'Efetuar coleta de dados rapida?',

	######## For Vista ########

	'DOWNLOAD_TMS_HELPER'	=> 'Baixar TMS Helper',

	######## New Memory Card Data Read 2008/03/31 ########

	'REGISTERED_FOLDER'	=> 'Pasta Retistrada',
	'REGISTER'		=> 'Registrar',
	'UNREGISTER'		=> 'Cancelar',

	######## End of Data ########

	'END_OF_DATA'			=> 'END_OF_DATA'	);
}

###################################################################################################
# Stop Cause Strings
###################################################################################################

sub load_stop_cause_str_jat710
{
  return (

	'0000'		=> 'PARAGEM DE URDUME',
	'0001'		=> 'PARAGEM DA OURELA FALSA',
	'0002'		=> 'PARAGEM DO LENO DIREITO',
	'0003'		=> 'PARAGEM DO LENO ESQUERDO',
	'0004'		=> 'PARAGEM DE TRAMA POR WF1 (COR1)',
	'0005'		=> 'PARAGEM DE TRAMA POR WF1 (COR2)',
	'0006'		=> 'PARAGEM DE TRAMA POR WF1 (COR3)',
	'0007'		=> 'PARAGEM DE TRAMA POR WF1 (COR4)',
	'0008'		=> 'PARAGEM DE TRAMA POR WF1 (COR5)',
	'0009'		=> 'PARAGEM DE TRAMA POR WF1 (COR6)',
	'0010'		=> 'PARAGEM DE TRAMA POR WF2 (COR1)',
	'0011'		=> 'PARAGEM DE TRAMA POR WF2 (COR2)',
	'0012'		=> 'PARAGEM DE TRAMA POR WF2 (COR3)',
	'0013'		=> 'PARAGEM DE TRAMA POR WF2 (COR4)',
	'0014'		=> 'PARAGEM DE TRAMA POR WF2 (COR5)',
	'0015'		=> 'PARAGEM DE TRAMA POR WF2 (COR6)',
	'0016'		=> 'PARAGEM DE TRAMA POR SENSOR DE BOBINA (COR1)',
	'0017'		=> 'PARAGEM DE TRAMA POR SENSOR DE BOBINA (COR2)',
	'0018'		=> 'PARAGEM DE TRAMA POR SENSOR DE BOBINA (COR3)',
	'0019'		=> 'PARAGEM DE TRAMA POR SENSOR DE BOBINA (COR4)',
	'0020'		=> 'PARAGEM DE TRAMA POR SENSOR DE BOBINA (COR5)',
	'0021'		=> 'PARAGEM DE TRAMA POR SENSOR DE BOBINA (COR6)',
	'0025'		=> 'ROLO DE TECIDO Á SER RETIRADO',
	'0027'		=> 'TECLA [STOP] APERTADA',
	'0028'		=> 'BOTÃO DE PARAGEM DE EMERGÊNCIA APERTADO',
	'1502'		=> 'TAPO:SEM FUNCIONAMENTO (NÃO HÁ TRAMA DEFEITUOSA)',
	'1503'		=> 'TAPO:FALHA NO PROCESSO (FIO DE TRAMA RETIRADO DEMASIADO CURTO)',
	'1504'		=> 'TAPO:FALHA NO PROCESSO (FIO DE TRAMA RETIRADO DEMASIADO COMPRIDO)',
	'2101'		=> 'PARAGEM POR CONTROLE REMOTO',
	'2150'		=> 'DECLARAÇAO (PROBLEMA MAQUINA)',
	'2151'		=> 'DECLARAÇAO (REPARAR)',
	'2153'		=> 'DECLARAÇAO (FIM DO ROLO DE URDUME)',
	'2154'		=> 'DECLARAÇAO (RETIRAR A PEÇA)',
	'2155'		=> 'DECLARACÃO (CHAMADA DO SUPERVISOR)',
	'2414'		=> 'PARADA DE URDUME (FUNDO)',
	'2415'		=> 'PARADA DE URDUME (FELPA)',
	'2420'		=> 'COMPRIMENTO PEÇA (NORMAL)',
	'2421'		=> 'COMPRIMENTO PEÇA (ADITIONAL)',
	'2422'		=> 'COMPRIMENTO PEÇA (CORTE)',
	'2430'		=> 'PARADA POR NO. DE LOTE',

	'0023'		=> 'CILINDRO PUXADOR DA OURELA-FALSA ENROLADO',
	'0024'		=> 'BARREIRA DE LUZ INTERROMPIDA (DISPOSITIVO DE SEGURANÇA ATIVADO)',
	'0026'		=> 'SINALIZAÇÂÃO DA RETIRADA DO ROLO DE TECIDO',
	'0031'		=> 'PARAGEM DO LENO CENTRO',
	'0032'		=> 'BARREIRA DE LUZ DEFEITUOSA',
	'0101'		=> 'LUBRIFICAÇÂÃO TERMINOU',
	'0102'		=> 'FALHA NA LUBRIFICAÇÂÃO',
	'0103'		=> 'CONTROLE PRINC.:OS VALORES DA PROGRAMAÇÂÃO FORAM INIÇIALIZADOS',
	'0105'		=> 'CHAPA-PROTETORA DO ACIONAMENTO PRINCIPAL NÃO FOI COLOCADA',
	'0108'		=> 'INSERçÂÃO EM MARCHA LENTA (ON)',
	'0110'		=> 'GUARDA-TRAMA WF1 ESTÁ DESLIGADO, MODO FEELER',
	'0111'		=> 'MAQUINETA: NIVELAMENTO ON',
	'0112'		=> 'NIVELAçÂÃO DA CALA: AUTOMÀTICO: POSIçÂÃO INCORRETA',
	'0113'		=> 'NIVELAçÂÃO DA CALA: TRAVADO',
	'0114'		=> 'NIVELAçÂÃO DA CALA: POSIçÂÃO NORMAL SEM SINAL',
	'0115'		=> 'NIVELAçÂÃO DA CALA: INTERROPIDO PELA TECLA STOPP',
	'0116'		=> 'DETECTOR DE ËLEO PARADO (APARELHO FORMAçÂÃO DE CALA)',
	'0117'		=> 'LUBRIFICAçÂÃO ATIVADO',
	'0118'		=> 'FALHA NA LUBRIFICAçÂÃO (PRESSÃO MUITO BAIXA)',
	'0119'		=> 'FALHA NA LUBRIFICAçÂÃO (PRESSÃO MUITO ALTA)',
	'0120'		=> 'NIVELAçÂÃO DA CALA: ERRO TIME-OUT',
	'0121'		=> 'NIVELAçÂÃO DA CALA: SINAL DO SENSOR INCORRETO',
	'0122'		=> 'BOMBA DE ÓLEO ANORMAL (APARELHO FORMAçÂÃO DE CALA)',
	'0123'		=> 'GUARDA-URDUME DESLIGADO',
	'0124'		=> 'SENSOR DA OURELA DE CORTE DESLIGADO',
	'0125'		=> 'SENSOR DO GIRO INGLÊS DESLIGADO',
	'0126'		=> 'SENSOR DE WF1 DESLIGADO',
	'0127'		=> 'SENSOR DE WF2 DESLIGADO',
	'0128'		=> 'SENSOR DE CONTA-ESPIRAS DESLIGADO',
	'0129'		=> 'SENSOR DE AQUECIMENTO DO MOTOR SOPRADOR DESLIGADO',
	'0130'		=> 'ESTROBOSCÓPIO ON',
	'0131'		=> 'PARAGEM DE DEMO',
	'0132'		=> 'PUSH [RELEASE SINGLE TURN]-SWITCH',
	'0133'		=> 'GUARDA-URDUME DESLIGADO (INFERIOR)',
	'0134'		=> 'GUARDA-URDUME DESLIGADO (SUPERIOR)',
	'0135'		=> 'WF1 SIGNALS LESS',
	'0136'		=> 'BARREIRA DE LUZ DESLIGADO',
	'0200'		=> 'TECLA [START] DEFEITUOSA',
	'0201'		=> 'TECLA [STOP] DEFEITUOSA',
	'0202'		=> 'TECLA [REVERSE] DEFEITUOSA',
	'0203'		=> 'TECLA [FORWARD] DEFEITUOSA',
	'0204'		=> 'TECLA [INTERLOCK] DEFEITUOSA',
	'0205'		=> 'INTERRUPTOR DO CONTROLE DO USO DAS DUAS MÃOS DEFEITUOSO',
	'0206'		=> 'TECLA [RELEASE BRAKE] DEFEITUOSA',
	'0207'		=> 'FALHA NA VOLTAGEM DO FREIO MAGNÉTICO',
	'0210'		=> 'MOTOR PRINCIPAL SOBRECARREGADO',
	'0211'		=> 'FALHA 140 VDC',
	'0212'		=> 'FALHA 24 VDC1',
	'0213'		=> 'FALHA 24 VDC2',
	'0214'		=> 'FALHA 24 VDC4',
	'0215'		=> 'FALHA 48 VDC',
	'0216'		=> 'FALHA 15 VDC',
	'0217'		=> 'FALHA P15 VDC',
	'0218'		=> 'FALHA M15 VDC',
	'0219'		=> 'FALHA12 VDC',
	'0220'		=> 'FALHA5 VDC',
	'0221'		=> 'GUARDA-URDUME DESCONECTADO',
	'0222'		=> 'MOTOR PRINCIPAL SUPERAQUECIDO',
	'0223'		=> 'CODIFICADOR ANGULAR, ERRO DA FASE Z',
	'0224'		=> 'CODIFICADOR ANGULAR, ERRO DA FASE A OU B',
	'0225'		=> 'CONTROLE PRINC.: TENSÃO DA BATERIA BAIXA',
	'0226'		=> 'MOTOR SOPRADOR SUBCARREGADO',
	'0227'		=> 'FALHA DO DISPOSITIVO DE SEGURANÇA',
	'0228'		=> 'AQUEÇA CORTADOR TROUBLE',
	'0229'		=> 'FALHA NA VOLTAGEM DO FREIO MAGNÉTICO (EM OPERAÇÂÃO)',
	'0280'		=> 'FALHA DA PLACA DO CONTROLE PRINCIPAL',
	'0281'		=> 'ERRO CH0 ETHERNET',
	'0282'		=> 'ERRO CH1 ETHERNET',
	'0300'		=> 'FALHA DO INVERTER OU MARCHA LENTA SOBRECARREGADA',
	'0301'		=> 'DINAMOMETRO DO FREIO MAGNÉTICO BAIXO',
	'0302'		=> 'FALHA DO GUARDA-TRAMAS WF1',
	'0303'		=> 'FALHA DO GUARDA-TRAMAS WF2',
	'0304'		=> 'FALTA DO SINAL DA FASE Z DO CODIFICADOR ANGULAR (EM OPERAÇÂÃO)',
	'0305'		=> 'IMPULSO DE ROTAÇÂÃO P/ TRÁS DO CODIFICADOR ANGULAR (EM OPERAÇÂÃO)',
	'0306'		=> 'ERRO AO CONTAR OS IMPULSOS DO CODIFICADOR ANGULAR (EM OPERAÇÂÃO)',
	'0307'		=> 'FALHA DO CONTA-ESPIRAS',
	'0308'		=> 'SINAIS DO CONTA-ESPIRAS MAIOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR1)',
	'0309'		=> 'SINAIS DO CONTA-ESPIRAS MAIOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR2)',
	'0310'		=> 'SINAIS DO CONTA-ESPIRAS MAIOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR3)',
	'0311'		=> 'SINAIS DO CONTA-ESPIRAS MAIOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR4)',
	'0312'		=> 'SINAIS DO CONTA-ESPIRAS MAIOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR5)',
	'0313'		=> 'SINAIS DO CONTA-ESPIRAS MAIOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR6)',
	'0314'		=> 'SINAIS DO CONTA-ESPIRAS MENOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR1)',
	'0315'		=> 'SINAIS DO CONTA-ESPIRAS MENOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR2)',
	'0316'		=> 'SINAIS DO CONTA-ESPIRAS MENOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR3)',
	'0317'		=> 'SINAIS DO CONTA-ESPIRAS MENOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR4)',
	'0318'		=> 'SINAIS DO CONTA-ESPIRAS MENOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR5)',
	'0319'		=> 'SINAIS DO CONTA-ESPIRAS MENOR QUE O NÚMERO DE ESPIRAS EFETIVOS (COR6)',
	'0320'		=> 'ABS: FALHA EM DETECTAR A POSICÃO INICIAL (COR 1)',
	'0321'		=> 'ABS: FALHA EM DETECTAR A POSICÃO INICIAL (COR 2)',
	'0322'		=> 'ABS: FALHA EM DETECTAR A POSICÃO INICIAL (COR 3)',
	'0323'		=> 'ABS: FALHA EM DETECTAR A POSICÃO INICIAL (COR 4)',
	'0324'		=> 'ABS: FALHA EM DETECTAR A POSICÃO INICIAL (COR 5)',
	'0325'		=> 'ABS: FALHA EM DETECTAR A POSICÃO INICIAL (COR 6)',
	'0326'		=> 'ABS: ERRO NO TEMPO DE CRUZAR (COR 1)',
	'0327'		=> 'ABS: ERRO NO TEMPO DE CRUZAR (COR 2)',
	'0328'		=> 'ABS: ERRO NO TEMPO DE CRUZAR (COR 3)',
	'0329'		=> 'ABS: ERRO NO TEMPO DE CRUZAR (COR 4)',
	'0330'		=> 'ABS: ERRO NO TEMPO DE CRUZAR (COR 5)',
	'0331'		=> 'ABS: ERRO NO TEMPO DE CRUZAR (COR 6)',
	'0332'		=> 'ABS: ALARME FOI GERADO (COR 1)',
	'0333'		=> 'ABS: ALARME FOI GERADO (COR 2)',
	'0334'		=> 'ABS: ALARME FOI GERADO (COR 3)',
	'0335'		=> 'ABS: ALARME FOI GERADO (COR 4)',
	'0336'		=> 'ABS: ALARME FOI GERADO (COR 5)',
	'0337'		=> 'ABS: ALARME FOI GERADO (COR 6)',
	'0403'		=> 'CONTROLE PRINC.: FALHA DA COMMUNICAçÂÃO DE DADOS(SOMIC ch0)',
	'0404'		=> 'CONTROLE PRINC.: FALHA DA COMMUNICAçÂÃO DE DADOS(SOMIC ch1)',
	'0405'		=> 'PARADA DE EMERGÊNCIA EM FUNCÃO DE FALHA DE ENERGIA',
	'0500'		=> 'Substitua a tesoura de trama',
	'0501'		=> 'Provê manualmente com graxa.',
	'0502'		=> 'Provê manualmente com caixa de engrenagem.',
	'0503'		=> 'Provê manualmente com graxa do desenrolador.',
	'0504'		=> 'Provê manualmente com caixa de excentricos.',
	'1000'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DE EMERGÊNCIA DO LET-OFF',
	'1001'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DO LET-OFF',
	'1002'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DO NWP(LET-OFF)',
	'1003'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO NWP(LET-OFF)',
	'1004'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO LET-OFF',
	'1005'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DA LET-OFF',
	'1006'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LET-OFF P/ ALTERAÇÃO DO LIGAM/TO',
	'1007'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LET-OFF P/ PROGRAM. DO LIGAM/TO',
	'1008'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LET-OFF P/ MARCA',
	'1009'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LET-OFF P/ AVANÇO DO TECIDO',
	'1010'		=> 'MODO DE PUXAR',
	'1011'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LET-OFF P/ MODO DE PUXAR',
	'1050'		=> 'CONTROLE PRINC.:TENSÃO DE URDUME DEMASIADO ALTA',
	'1051'		=> 'CONTROLE PRINC.:TENSÃO DE URDUME DEMASIADO BAIXA',
	'1100'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DE EMERGÊNCIA DO LET-OFF(SUPERIOR)',
	'1101'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DO LET-OFF(SUPERIOR)',
	'1102'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DO NWP(LET-OFF SUPERIOR)',
	'1103'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO NWP(LET-OFF SUPERIOR)',
	'1104'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO LET-OFF(SUPERIOR)',
	'1105'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DA LET-OFF(SUPERIOR)',
	'1106'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(SUP.) P/ ALTER. DO LIGAMENTO',
	'1107'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(SUP.) P/ PROGR. DO LIGAMENTO',
	'1108'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(SUP.) P/ AVANÇO DO TECIDO',
	'1109'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(SUPERIOR) P/ MARCA',
	'1200'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DE EMERGÊNCIA DO LET-OFF(DIREITA)',
	'1201'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DO LET-OFF(DIREITA)',
	'1202'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DO NWP(LET-OFF DIREITA)',
	'1203'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO NWP(LET-OFF DIREITA)',
	'1204'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO LET-OFF(DIREITA)',
	'1205'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DA LET-OFF(DIREITA)',
	'1206'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(DIR.) P/ ALTER. DO LIGAMENTO',
	'1207'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(DIR.) P/ PROGR. DO LIGAMENTO',
	'1208'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(DIR.) P/ AVANÇO DO TECIDO',
	'1209'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(DIREITA) P/ MARCA',
	'1300'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DE EMERGÊNCIA DO LET-OFF(ESQUERDA)',
	'1301'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DO LET-OFF(ESQUERDA)',
	'1302'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DO NWP(LET-OFF ESQUERDA)',
	'1303'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO NWP(LET-OFF ESQUERDA)',
	'1304'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO LET-OFF(ESQUERDA)',
	'1305'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DA LET-OFF(ESQUERDA)',
	'1306'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(ESQ.) P/ ALTER. DO LIGAMENTO',
	'1307'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(ESQ.) P/ PROGR. DO LIGAMENTO',
	'1308'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(ESQ.) P/ AVANÇO DO TECIDO',
	'1309'		=> 'CONTROLE PRINC.:ERRO DE COMUNIC. DO LET-OFF(ESQ.) P/ MARCA',
	'1400'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DE EMERGÊNCIA DO TAKE-UP',
	'1401'		=> 'TAKE-UP:ERRO DO SERVO AMPLIFIER',
	'1402'		=> 'TAKE-UP:A UNIDADE SERVO AMPLIFIER FORÇA DEMAIS',
	'1403'		=> 'TAKE-UP:ERRO DO RESOLVER FEEDBACK',
	'1404'		=> 'TAKE-UP:SERVO AMP. TEMPORARIAMENTE SOBRECARREGADO',
	'1405'		=> 'TAKE-UP:SERVOMOTOR SUPERAQUECIDO (DETECTADO P/ SOFTWARE)',
	'1406'		=> 'TAKE-UP:SERVO AMP. AMPLIFICADOR DO CONTROLE DE VELOCIDADE SATURADO',
	'1407'		=> 'TAKE-UP:SERVO AMP. CORRENTE DEMASIADO ALTA (DETECTADO P/ SOFTWARE)',
	'1408'		=> 'TAKE-UP:SERVO AMP. ERRO DO CONTACTOR DO CIRCUITO PRINCIPAL',
	'1409'		=> 'TAKE-UP:CABO DO RESOLVER QUEBRADO',
	'1410'		=> 'TAKE-UP:FONTE DA ALIMENTAÇÂÃO PRINCIPAL (AC) DO SERVO AM. FALHOU',
	'1411'		=> 'TAKE-UP:SOBRETENSÃ0 MANDADA P/ O SERVO AMP.',
	'1412'		=> 'TAKE-UP:SERVO AMP. ERRO IPM',
	'1413'		=> 'CILINDRO DE COMANDO DO TECIDO EM ROTAÇÂÃO PARA FERNTE',
	'1414'		=> 'CILINDRO DE COMANDO DO TECIDO EM ROTAÇÂÃO PARA TRÁS',
	'1415'		=> 'TAKE-UP:VELOCÍMETRO FORÇADO',
	'1416'		=> 'TAKE-UP:SERVO AMP. ERRO DE PARAGEM DE EMERGÊNCIA',
	'1417'		=> 'TAKE-UP:SERVO AMP. ERRO AO RESOLVER A PARAGEM DE EMERGÊNCIA',
	'1418'		=> 'TAKE-UP:SINAL DE FASE DO CODIFICADOR ANGULAR ANORMAL',
	'1419'		=> 'TAKE-UP:ERRO DE COMMUNICAçÂÃO( TEMPO PARA FORA )',
	'1420'		=> 'TAKE-UP:ERRO DE COMMUNICAçÂÃO( DADOS ANORMAIS )',
	'1421'		=> 'TAKE-UP:ERRO DE COMMUNICAçÂÃO( RESPOSTA ANORMAL )',
	'1422'		=> 'CONTROLE PRINC.:FALHA AO TAKE-UP PARA O FELL-FWD SINAL',
	'1423'		=> 'TAKE-UP:ERRO DE COMMUNICAçÂÃO( SINAL DE DIREçÂÃO )',
	'1450'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DO TAKE-UP(BW)',
	'1470'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DE EMERGÊNCIA DO TAKEUP',
	'1471'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DO TAKEUP',
	'1472'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DO TAKEUP',
	'1473'		=> 'CONTROLE PRINC.:ERRO DE COMMUNICAçÂÃO DO TAKEUP',
	'1474'		=> 'CONTROLE PRINC.:RESPOSTA NEGATIVA DO TAKEUP',
	'1475'		=> 'CONTROLE PRINC.:ERRO TIME-OUT, SEM RESPOSTA DO TAKEUP',
	'1476'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO TAKEUP P/ ALTERAÇÃO DO LIGAM/TO',
	'1477'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO TAKEUP P/ PROGR. DO LIGAMENTO',
	'1478'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO TAKEUP P/ MARCA',
	'1479'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO TAKEUP P/ AVANÇO DO TECIDO',
	'1480'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LETOFF P/ Estado de operação',
	'1490'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LETOFF P/ opções',
	'1491'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LETOFF(ESQUERDA) P/ opções',
	'1492'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LETOFF(DIREITA) P/ opções',
	'1493'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO LETOFF(SUPERIOR) P/ opções',
	'1494'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÃO DO TAKEUP P/ opções',
	'1495'		=> 'LETOFF: REINICIALIZAÇÃO',
	'1496'		=> 'LETOFF(ESQUERDA): REINICIALIZAÇÃO',
	'1497'		=> 'LETOFF(DIREITA): REINICIALIZAÇÃO',
	'1498'		=> 'LETOFF(SUPERIOR): REINICIALIZAÇÃO',
	'1499'		=> 'TAKEUP: REINICIALIZAÇÃO',
	'1500'		=> 'TAPO:EM FUNCIONAMENTO, MÁQUINA BLOQUEIADA',
	'1506'		=> 'TAPO:FALHA EM ENROLAR FIO',
	'1600'		=> 'APC:PRESSÃO DE AR DO SISTEMA BAIXA',
	'1601'		=> 'APC:LIMITE SUPERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 1',
	'1602'		=> 'APC:LIMITE INFERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 1',
	'1603'		=> 'APC:LIMITE SUPERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 2',
	'1604'		=> 'APC:LIMITE INFERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 2',
	'1605'		=> 'APC:LIMITE SUPERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 3',
	'1606'		=> 'APC:LIMITE INFERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 3',
	'1607'		=> 'APC:LIMITE SUPERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 4',
	'1608'		=> 'APC:LIMITE INFERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 4',
	'1609'		=> 'APC:LIMITE SUPERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 5',
	'1610'		=> 'APC:LIMITE INFERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 5',
	'1611'		=> 'APC:LIMITE SUPERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 6',
	'1612'		=> 'APC:LIMITE INFERIOR DA PRESSÃO DA TUBEIRA PRINCIPAL 6',
	'1613'		=> 'APC:LIMITE SUPERIOR DA PRESSÃO DAS ESTAFETAS',
	'1614'		=> 'APC:LIMITE INFERIOR DA PRESSÃO DAS ESTAFETAS',
	'1615'		=> 'APC:LIMITE SUPERIOR DA PRESSÃO DA TUBEIRA DE ESTIRAGEM',
	'1616'		=> 'APC:LIMITE INFERIOR DA PRESSÃO DA TUBEIRA DE ESTIRAGEM',
	'1650'		=> 'VALOR TW (CHEGADA DA TRAMA) FORA DO ÂMBITO PROGRAMADO (COR 1)',
	'1651'		=> 'VALOR TW (CHEGADA DA TRAMA) FORA DO ÂMBITO PROGRAMADO (COR 2)',
	'1652'		=> 'VALOR TW (CHEGADA DA TRAMA) FORA DO ÂMBITO PROGRAMADO (COR 3)',
	'1653'		=> 'VALOR TW (CHEGADA DA TRAMA) FORA DO ÂMBITO PROGRAMADO (COR 4)',
	'1654'		=> 'VALOR TW (CHEGADA DA TRAMA) FORA DO ÂMBITO PROGRAMADO (COR 5)',
	'1655'		=> 'VALOR TW (CHEGADA DA TRAMA) FORA DO ÂMBITO PROGRAMADO (COR 6)',
	'1670'		=> 'ITC: SENSOR DA FALHA DA PRESSÃO',
	'1700'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DE EMERGÊNCIA DO SC INVERTER',
	'1701'		=> 'CONTROLE PRINC.:SINAL DE PARAGEM DO SC INVERTER',
	'1702'		=> 'CONTROLE PRINC.:ERRO DE COMUNICAÇÂÃO, COM SC INVERTER',
	'1703'		=> 'SC INVERTER:SOBREAQUECIDO',
	'1704'		=> 'SC INVERTER:SOBRECORRENTE',
	'1705'		=> 'SC INVERTER:TENSÃO DEMASIADO ALTA',
	'1706'		=> 'SC INVERTER:TENSÃO DEMASIADO BAIXA',
	'1707'		=> 'SC INVERTER:ERRO NA REAÇÂÃO DO MOTOR PRINCIPAL',
	'1708'		=> 'SC INVERTER:ERRO NA REAÇÂÃO DO MOTOR PRINCIPAL',
	'1709'		=> 'SC INVERTER:SINAL DE PARAGEM DE EMERGÊNCIA DO CONTROLE PRINC.',
	'1710'		=> 'SC INVERTER:FALHA IPM',
	'1711'		=> 'SC INVERTER:PROGRAM REWRITABLE STATE',
	'1712'		=> 'SC INVERTER:FAILURE OF PROGRAM WRITING',
	'1800'		=> 'MAQUINETA:BOMBA DE ÓLEO ANORMAL',
	'1801'		=> 'MAQUINETA:SINAIS ANORMAIS DOS SENSORES DE APROXIMAÇÂÃO',
	'1802'		=> 'MAQUINETA:INVERS.DO SENTIDO DE ROTAÇ.DE FRENTE P/ TRÁS PROIBIDA',
	'1803'		=> 'MAQUINETA:INVERS.DO SENTIDO DA ROTAÇ.DE TRÁS P/ FRENTE PROIBIDA',
	'1804'		=> 'MAQUINETA:USO MARCHA LENTA DENTRO DA ZONA DE BLOQUEIO(FRENTE P/TRÁS)',
	'1805'		=> 'MAQUINETA:USO MARCHA LENTA DENTRO DA ZONA DE BLOQUIEO(TRÁS P/FRENTE)',
	'1806'		=> 'MAQUINETA:ELETROÍMÃ NO.01 AVARIADO',
	'1807'		=> 'MAQUINETA:ELETROÍMÃ NO.02 AVARIADO',
	'1808'		=> 'MAQUINETA:ELETROÍMÃ NO.03 AVARIADO',
	'1809'		=> 'MAQUINETA:ELETROÍMÃ NO.04 AVARIADO',
	'1810'		=> 'MAQUINETA:ELETROÍMÃ NO.05 AVARIADO',
	'1811'		=> 'MAQUINETA:ELETROÍMÃ NO.06 AVARIADO',
	'1812'		=> 'MAQUINETA:ELETROÍMÃ NO.07 AVARIADO',
	'1813'		=> 'MAQUINETA:ELETROÍMÃ NO.08 AVARIADO',
	'1814'		=> 'MAQUINETA:ELETROÍMÃ NO.09 AVARIADO',
	'1815'		=> 'MAQUINETA:ELETROÍMÃ NO.10 AVARIADO',
	'1816'		=> 'MAQUINETA:ELETROÍMÃ NO.11 AVARIADO',
	'1817'		=> 'MAQUINETA:ELETROÍMÃ NO.12 AVARIADO',
	'1818'		=> 'MAQUINETA:ELETROÍMÃ NO.13 AVARIADO',
	'1819'		=> 'MAQUINETA:ELETROÍMÃ NO.14 AVARIADO',
	'1820'		=> 'MAQUINETA:ELETROÍMÃ NO.15 AVARIADO',
	'1821'		=> 'MAQUINETA:ELETROÍMÃ NO.16 AVARIADO',
	'1822'		=> 'MAQUINETA:ELETROÍMÃ NO.17 AVARIADO',
	'1823'		=> 'MAQUINETA:ELETROÍMÃ NO.18 AVARIADO',
	'1824'		=> 'MAQUINETA:ELETROÍMÃ NO.19 AVARIADO',
	'1825'		=> 'MAQUINETA:ELETROÍMÃ NO.20 AVARIADO',
	'2000'		=> 'LENO: DADOS ANORMAIS',
	'2001'		=> 'LENO(DIREITA): ALARME SINAL',
	'2002'		=> 'LENO(ESQUERDA): ALARME SINAL',
	'2003'		=> 'LENO(DIREITA): FALHA AO DESCUBRA ORIGEM',
	'2004'		=> 'LENO(ESQUERDA): FALHA AO DESCUBRA ORIGEM',
	'2005'		=> 'LENO(DIREITA): SERVO AMP. SOBRECORRENTE',
	'2006'		=> 'LENO(ESQUERDA): SERVO AMP. SOBRECORRENTE',
	'2100'		=> 'BLOQUEIO DO CONTROLE REMOTO',
	'2102'		=> 'CONTROLE PRINC.:DESENHO ERRADO',
	'2103'		=> 'CONTROLE PRINC.:RAPPORTE DE CORES ERRADO',
	'2104'		=> 'CONTROLE PRINC.:DADOS DA DENSIDAD ERRADO',
	'2105'		=> 'CONTROLE PRINC.:SINAL COM DEFEITO NA FELPA',
	'2106'		=> 'CONTROLE PRINC.:DESENHO ERRADO (CALA)',
	'2107'		=> 'CONTROLE PRINC.:INICIAR LIGAMENTO PARA PRIMEIRA TRAMA',
	'2108'		=> 'CONTROLE PRINC.:RELÓGIO ANORMAL',
	'2109'		=> 'O RELOJO DA MÁQUINA ESTÁ INCORRETO',
	'2110'		=> 'CONTROLE PRINC.:DADOS DA DENSIDAD ERRADO',
	'2170'		=> 'PARADA MONITORANDO AGORA',
	'2200'		=> 'MÁQUINA NÃO FUNCIONA ENQUANTO O ENFIADOR AUTOMÁTICO ESTÁ OPERANDO.',
	'2201'		=> 'FALHA AO SOPRAR OS RESTOS DE FIO DA BOBINA 1',
	'2202'		=> 'FALHA AO SOPRAR OS RESTOS DE FIO DA BOBINA 2',
	'2203'		=> 'FALHA AO SOPRAR OS RESTOS DE FIO DA BOBINA 3',
	'2204'		=> 'FALHA AO SOPRAR OS RESTOS DE FIO DA BOBINA 4',
	'2205'		=> 'FALHA AO SOPRAR OS RESTOS DE FIO DA BOBINA 5',
	'2206'		=> 'FALHA AO SOPRAR OS RESTOS DE FIO DA BOBINA 6',
	'2207'		=> 'FALHA AO SOPRAR OS RESTOS DE FIO DA BOBINA 7',
	'2208'		=> 'FALHA AO SOPRAR OS RESTOS DE FIO DA BOBINA 8',
	'2210'		=> 'O FIO DA BOBINA 1 ACABOU-SE',
	'2211'		=> 'O FIO DA BOBINA 2 ACABOU-SE',
	'2212'		=> 'O FIO DA BOBINA 3 ACABOU-SE',
	'2213'		=> 'O FIO DA BOBINA 4 ACABOU-SE',
	'2214'		=> 'O FIO DA BOBINA 5 ACABOU-SE',
	'2215'		=> 'O FIO DA BOBINA 6 ACABOU-SE',
	'2216'		=> 'O FIO DA BOBINA 7 ACABOU-SE',
	'2217'		=> 'O FIO DA BOBINA 8 ACABOU-SE',
	'2218'		=> 'O SENSOR DA PONTA DA TRAMA DETECTOU UM SINAL 1',
	'2219'		=> 'O SENSOR DA PONTA DA TRAMA DETECTOU UM SINAL 2',
	'2220'		=> 'O SENSOR DA PONTA DA TRAMA DETECTOU UM SINAL 3',
	'2221'		=> 'O SENSOR DA PONTA DA TRAMA DETECTOU UM SINAL 4',
	'2222'		=> 'SENSOR 1 DA PONTA DA TRAMA ANORMAL (QUEBRA DO CABO)',
	'2223'		=> 'SENSOR 2 DA PONTA DA TRAMA ANORMAL (QUEBRA DO CABO)',
	'2224'		=> 'SENSOR 3 DA PONTA DA TRAMA ANORMAL (QUEBRA DO CABO)',
	'2225'		=> 'SENSOR 4 DA PONTA DA TRAMA ANORMAL (QUEBRA DO CABO)',
	'2226'		=> 'CHEGADA DO SINAL DO SENSOR DA PONTA DA TRAMA PASSOU DO TEMPO DETERMINADO',
	'2227'		=> 'NÃO HÁ SINAL DO SENSOR DE SUPERVISÃO DAS BOBINAS',
	'2228'		=> 'APC PRESSÃO ESTÁ SENDO INIÇIALIZADA',
	'2229'		=> 'MANEJE O FIO DE TRAMA MANUALMENTE',
	'2230'		=> 'VERIFIQUE SE HÁ UMA PONTA DE TRAMA NO SENSOR',
	'2231'		=> 'TROCAR BOBINAS VAZÍAS',
	'2232'		=> 'SENSOR DE BOBINAS E SENSOR DE TRAMA NÃO ATIVADOS',
	'2233'		=> 'FALHA EM INICIALIZAR PRESSÃO APC',
	'2234'		=> 'O SENSOR DA PONTA DA TRAMA DETECTOU UM SINAL 5',
	'2235'		=> 'O SENSOR DA PONTA DA TRAMA DETECTOU UM SINAL 6',
	'2236'		=> 'SENSOR 5 DA PONTA DA TRAMA ANORMAL (QUEBRA DO CABO)',
	'2237'		=> 'SENSOR 6 DA PONTA DA TRAMA ANORMAL (QUEBRA DO CABO)',
	'2300'		=> 'CONTROLE PRINCIPAL: FALHA NA COMUNICACÃO COM AGREGADO FORMACÃO DE CALA',
	'2301'		=> 'CONTROLE PRINCIPAL: SINAL DE PARADA DE EMERGÊNCIA DA FORMACÃO DE CALA',
	'2302'		=> 'CONTROLE PRINCIPAL: INICIALIZACÃO DO EIXO PRINCIPAL INCOMPLETA',
	'2303'		=> 'CONTROLE PRINCIPAL: FALHA EM COMUNICAR O ESTADO DA FORMACÃO DA CALA',
	'2304'		=> 'CONTROLE PRINCIPAL: COMUNICACÃO DE DESNIVELAR A FORMACÃO DA CALA FALHOU',
	'2305'		=> 'CONTROLE PRINCIPAL: COMUNICACÃO DE INCIALIZAR OS QUADROS FALHOU',
	'2306'		=> 'CONTROLE PRINCIPAL: COMUNICACÃO DE NIVELAR A FORMACÃO DA CALA FALHOU',
	'2307'		=> 'MOVIMENTO PF IMPOSSÍVEL, FORMACÃO DA CALA NAO FOI SINCRONIZADA',
	'2308'		=> 'NIVELAMENTO IMPOSSÍVEL, POSICÃO DOS QUADROS NAO FOI INICIALIZADA',
	'2309'		=> 'CONTROLE PRINCIPAL: RECEBEU UM SINAL DE PARADA DO AGREGADO FORMACÃO DA CALA',
	'2310'		=> 'ZONA DE USO DA MARCHA LENTA PROIBÍDO DURANTE O NIVELAMENTO DOS QUADROS',
	'2311'		=> 'CONTROLE PRINCIPAL: MOVIMENTO IMPOSSÍVEL, POS. EIXO PRINC. NAO RECONHECIDO',
	'2312'		=> 'CONTROLE PRINCIPAL: VERIFICANDO LIGAMENTO',
	'2400'		=> 'CONTROLE PRINC.: RESPOSTA ANORMAL JACQUARD',
	'2401'		=> 'CONTROLE PRINC.: SEM RESPOSTA JACQUARD',
	'2402'		=> 'CONTROLE PRINC.: DESENHO RENOVADO COM JACQUARD',
	'2403'		=> 'CONTROLE PRINC.: RAPPORTE DE CORES ERRADO DE JACQUARD',
	'2404'		=> 'CONTROLE PRINC.: DESENHO ERRADO',
	'2405'		=> 'CONTROLE PRINC.: TROCA DE DESENHO PARA DE JACQUARD',
	'2406'		=> 'CONTROLE PRINC.: SINAL DE STOP DE JACQUARD',
	'2407'		=> 'JACQUARD: MUDANçA DE TECIDO PARA FRENTE PROIBIDO',
	'2408'		=> 'JACQUARD: MUDANçA DE TECIDO PARA TRÀS PROIBIDO',
	'2410'		=> 'CONTROLE PRINC.: ALARME DO MOTOR COMANDO DE FELPA',
	'2411'		=> 'CONTROLE PRINC.: DADOS DE FELPA FORA DO ÂMBITO PROGRAMADO',
	'2417'		=> 'CONTROLE PRINC.: SINAL COM DEFEITO NA FELPA JACQUARD',
	'2418'		=> 'CONTROLE PRINC.: SINAL COM DEFEITO DE TENSÃO NO DESENROLADOR DE URDUME',
	'2419'		=> 'CONTROLE PRINC.: ANORMAL SINAL DE TENSÃO (FUNDO)',
	'2423'		=> 'CONTROLE PRINC.: SINAL DA FRANJA RECEBIDO DE JACQUARD',
	'2424'		=> 'RETIRAR ROLO DE TECIDO (FRANJAS)',
	'2425'		=> 'RETIRAR ROLO DE TECIDO (CORTAR)',
	'2426'		=> 'MAIN CONTROL: PATTERN 1ST PICK INITIALED',
	'2452'		=> 'CONTROLE PRINC.: ERRO DE COMMUNICAçÂÃO COM DESENROLADOR DE URDUME',
	'2470'		=> 'CONTROLE PRINCIPAL: CORREIA DENTADA DOS REINTRODUTORES DE OURELA QUEBRADA',
	'4500'		=> 'OURELA(DIR): SINAL DO SENSOR DE INICIALIZACÃO ANORMAL',
	'4501'		=> 'OURELA(DIR): SINAL DO SENSOR DE INICIALIZACÃO NÃO FOI DETECTADO',
	'4505'		=> 'OURELA(DIR): ALARME DO DRIVER FOI GERADO',
	'4506'		=> 'OURELA(DIR): SAÍDA DE PULSO ESTÁ ANORMAL',
	'4510'		=> 'OURELA(ESQ): SINAL DO SENSOR DE INICIALIZACÃO ANORMAL',
	'4511'		=> 'OURELA(ESQ): SINAL DO SENSOR DE INICIALIZACÃO NÃO FOI DETECTADO',
	'4515'		=> 'OURELA(ESQ): ALARME DO DRIVER FOI GERADO',
	'4516'		=> 'OURELA(ESQ): SAÍDA DE PULSO ESTÁ ANORMAL',

	######## End of Data ########

	'OTHER_STOP'	=> 'PARAGEM DE OUTRO'	);
}

###################################################################################################

sub load_stop_cause_str_lwt710
{
  return (

	'0000'		=> 'WARP STOP',
	'0001'		=> 'WASTE-SELVAGE STOP (FRONT)',
	'0002'		=> 'WASTE-SELVAGE STOP (REAR)',
	'0003'		=> 'FULL-LENO SELVAGE STOP (RIGHT-HAND)',
	'0004'		=> 'FULL-LENO SELVAGE STOP (LEFT-HAND)',
	'0005'		=> 'WEFT STOP (COLOR 1)',
	'0006'		=> 'WEFT STOP (COLOR 2)',
	'0007'		=> 'WEFT STOP (COLOR 3)',
	'0008'		=> 'WEFT STOP (COLOR 4)',
	'0009'		=> 'WEFT SUPPLY STOP (COLOR 1)',
	'0010'		=> 'WEFT SUPPLY STOP (COLOR 2)',
	'0011'		=> 'WEFT SUPPLY STOP (COLOR 3)',
	'0012'		=> 'WEFT SUPPLY STOP (COLOR 4)',
	'0013'		=> 'CLOTH BEAM TO BE DOFFED',
	'0026'		=> 'CLOTH BEAM DOFFING SIGNALLED',
	'0014'		=> '[STOP] SWITCH PRESSED',
	'0015'		=> 'EMERGENCY STOP BUTTON PRESSED',
	'0110'		=> 'FEELER IS OFF SETTING',
	'0126'		=> 'FEELER SENSOR OFF',
	'2100'		=> 'REMOTE CONTROL LOCK',
	'2101'		=> 'REMOTE CONTROL STOP',
	'2150'		=> 'DECLARE(M/C TROUBLE)',
	'2151'		=> 'DECLARE(MENDING)',
	'2153'		=> 'DECLARE(WARP OUT)',
	'2154'		=> 'DECLARE(CLOTH DOFFING)',
	'2155'		=> 'DECLARE(FOREMAN CALL ON)',

	'0023'		=> 'WASTE-SELVAGE ROLLER TANGLED',
	'0024'		=> 'LIGHT BARRIER INTERRUPTED (SAFETY DEVICE ON)',
	'0102'		=> 'OILING FAILED',
	'0105'		=> 'HANDLE COVER NOT INSTALLED',
	'0116'		=> 'OILING SENSOR STOP(SHEDDING MACHINE)',
	'0117'		=> 'OILING NOW( VALVE RESTORING )',
	'0118'		=> 'OILING FAILED( PRESSURE IS LOW )',
	'0119'		=> 'OILING FAILED( PRESSURE IS HIGH )',
	'0122'		=> 'ABNORMAL OIL PUMP(SHEDDING MACHINE)',
	'0137'		=> 'CLOSE WINDOW COVER',
	'0138'		=> 'WINDOW COVER SENSOR OFF',
	'0139'		=> 'WEFT BREAK STOP (COLOR 1)',
	'0140'		=> 'WEFT BREAK STOP (COLOR 2)',
	'0141'		=> 'WEFT BREAK STOP (COLOR 3)',
	'0142'		=> 'WEFT BREAK STOP (COLOR 4)',
	'0207'		=> 'BRAKE VOLTAGE FAILURE',
	'0210'		=> 'MAIN MOTOR OVERLOAD',
	'0211'		=> '140V[DCPS2] VDC FAILURE',
	'0212'		=> '24V[DCPS2] FAILURE',
	'0213'		=> '24V[DCPS4] FAILURE',
	'0214'		=> '24V[DCPS2] FAILURE',
	'0215'		=> '48V[DCPS2] FAILURE',
	'0216'		=> '12V[DCPS2] FAILURE',
	'0217'		=> 'P15V[DCPS10] FAILURE',
	'0218'		=> 'M15V[DCPS10] FAILURE',
	'0219'		=> '12V[DCPS3] FAILURE',
	'0220'		=> '5V FAILURE',
	'0221'		=> 'WARP DETECTOR DISCONNECTED',
	'0222'		=> 'MAIN MOTOR OVERHEAT',
	'0223'		=> 'ENCODER, Z-PHASE ERROR',
	'0224'		=> 'ENCODER, A- OR B-PHASE ERROR',
	'0225'		=> 'MAIN CONTROL:LOW BATTERY VOLTAGE',
	'0226'		=> 'BLOWER MOTOR OVERLOAD',
	'0227'		=> 'BLOWER MOTOR OVERLOAD',
	'0228'		=> 'SAFETY DEVICE FAILURE',
	'0229'		=> 'HEAT CUTTER TROUBLE',
	'0230'		=> 'BRAKE VOLTAGE FAIL (DRIVE)',
	'0280'		=> 'CPU BOARD FAILURE',
	'0281'		=> 'ETHERNET CH0 ERROR',
	'0282'		=> 'ETHERNET CH1 ERROR',
	'0300'		=> 'INVERTER FAILURE OR INCHING OVERLOAD',
	'0301'		=> 'LACK OF BRAKE TORQUE',
	'0302'		=> 'WF1 FAILURE',
	'0303'		=> 'WF2 FAILURE',
	'0304'		=> 'NO INPUT FROM ENCODER Z-PHASE (IN OPERATION)',
	'0305'		=> 'REVERSE-REV. PULSE FROM ENCODER (IN OPERATION)',
	'0306'		=> 'ENCODER FWD-REV. PULSE COUNT ERROR (IN OPERATION)',
	'0307'		=> 'WINDING SENSOR FAILURE',
	'0308'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 1)',
	'0309'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 2)',
	'0310'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 3)',
	'0311'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 4)',
	'0312'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 5)',
	'0313'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 6)',
	'0314'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 1)',
	'0315'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 2)',
	'0316'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 3)',
	'0317'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 4)',
	'0318'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 5)',
	'0319'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 6)',
	'0320'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 1)',
	'0321'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 2)',
	'0322'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 3)',
	'0323'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 4)',
	'0324'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 5)',
	'0325'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 6)',
	'0326'		=> 'ABS: CROSSING TIME ERROR (COLOR 1)',
	'0327'		=> 'ABS: CROSSING TIME ERROR (COLOR 2)',
	'0328'		=> 'ABS: CROSSING TIME ERROR (COLOR 3)',
	'0329'		=> 'ABS: CROSSING TIME ERROR (COLOR 4)',
	'0330'		=> 'ABS: CROSSING TIME ERROR (COLOR 5)',
	'0331'		=> 'SPINDLE: PULSE OVER',
	'0332'		=> 'ABS: ALARM GENERATED (COLOR 1)',
	'0333'		=> 'ABS: ALARM GENERATED (COLOR 2)',
	'0334'		=> 'ABS: ALARM GENERATED (COLOR 3)',
	'0335'		=> 'ABS: ALARM GENERATED (COLOR 4)',
	'0336'		=> 'ABS: ALARM GENERATED (COLOR 5)',
	'0403'		=> 'MAIN CONTROL: DATA COMMUNICATION FAILURE (SOMIC ch0)',
	'0404'		=> 'MAIN CONTROL: DATA COMMUNICATION FAILURE (SOMIC ch1)',
	'1000'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM LET-OFF',
	'1001'		=> 'MAIN CONTROL: STOP SIGNAL FROM LET-OFF',
	'1002'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH LET-OFF',
	'1003'		=> 'MAIN CONTROL: SEND ERROR, WITH LET-OFF',
	'1004'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM LET-OFF',
	'1005'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH LET-OFF',
	'1006'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR PATTERN CHANGE',
	'1007'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR PATTERN SETTING',
	'1008'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR STOP MARK SIGNAL',
	'1009'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR FELL-FWD SIGNAL',
	'1010'		=> 'BEAM PREPARE MODE',
	'1011'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR BEAM PREPARE MODE',
	'1050'		=> 'MAIN CONTROL:TOO HIGH WARP TENSION',
	'1051'		=> 'MAIN CONTROL:TOO LOW WARP TENSION',
	'1100'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM UPPER LET-OFF',
	'1101'		=> 'MAIN CONTROL: STOP SIGNAL FROM UPPER LET-OFF',
	'1102'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH UPPER LET-OFF',
	'1103'		=> 'MAIN CONTROL: SEND ERROR, WITH UPPER LET-OFF',
	'1104'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM UPPER LET-OFF',
	'1105'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH UPPER LET-OFF',
	'1106'		=> 'MAIN CONTROL: FAILURE TO UPPER LET-OFF FOR PATTERN CHANGE',
	'1107'		=> 'MAIN CONTROL: FAILURE TO UPPER LET-OFF FOR PATTERN SETTING',
	'1108'		=> 'MAIN CONTROL: FAILURE TO UPPER LET-OFF FOR STOP MARK SIGNAL',
	'1109'		=> 'MAIN CONTROL: FAILURE TO UPPER LET-OFF FOR FELL-FWD SIGNAL',
	'1200'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM RH_LET-OFF',
	'1201'		=> 'MAIN CONTROL: STOP SIGNAL FROM RH_LET-OFF',
	'1202'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH RH LET-OFF',
	'1203'		=> 'MAIN CONTROL: SEND ERROR, WITH RH LET-OFF',
	'1204'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM RH LET-OFF',
	'1205'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH RH LET-OFF',
	'1206'		=> 'MAIN CONTROL: FAILURE TO RH LET-OFF FOR PATTERN CHANGE',
	'1207'		=> 'MAIN CONTROL: FAILURE TO RH LET-OFF FOR PATTERN SETTING',
	'1208'		=> 'MAIN CONTROL: FAILURE TO RH LET-OFF FOR STOP MARK SIGNAL',
	'1209'		=> 'MAIN CONTROL: FAILURE TO RH LET-OFF FOR FELL-FWD SIGNAL',
	'1300'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM LH_LET-OFF',
	'1301'		=> 'MAIN CONTROL: STOP SIGNAL FROM LH_LET-OFF',
	'1302'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH LH LET-OFF',
	'1303'		=> 'MAIN CONTROL: SEND ERROR, WITH LH LET-OFF',
	'1304'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM LH LET-OFF',
	'1305'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH LH LET-OFF',
	'1306'		=> 'MAIN CONTROL: FAILURE TO LH LET-OFF FOR PATTERN CHANGE',
	'1307'		=> 'MAIN CONTROL: FAILURE TO LH LET-OFF FOR PATTERN SETTING',
	'1308'		=> 'MAIN CONTROL: FAILURE TO LH LET-OFF FOR STOP MARK SIGNAL',
	'1309'		=> 'MAIN CONTROL: FAILURE TO LH LET-OFF FOR FELL-FWD SIGNAL',
	'1400'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM TAKE-UP',
	'1401'		=> 'TAKE-UP:SERVO AMPLIFIER ERROR',
	'1402'		=> 'TAKE-UP:SERVO AMPLIFIER OVERSHOOT',
	'1403'		=> 'TAKE-UP:RESOLVER FEEDBACK ERROR',
	'1404'		=> 'TAKE-UP:SERVO AMP. TENTATIVELY OVERLOADED',
	'1405'		=> 'TAKE-UP:SERVOMOTOR OVERHEAT (SOFTWARE-DETECTED)',
	'1406'		=> 'TAKE-UP:SERVO AMP., SPEED CONTROL AMP. SATURATED',
	'1407'		=> 'TAKE-UP:SERVO AMP. OVERCURRENT (SOFTWARE-DETECTED)',
	'1408'		=> 'TAKE-UP:SERVO AMP., MAIN CIRCUIT CONTACTOR ERROR',
	'1409'		=> 'TAKE-UP:RESOLVER CABLE BROKEN',
	'1410'		=> 'TAKE-UP:DROPPED MAIN AC POWER SUPPLY VOLTAGE TO SERVO AMP.',
	'1411'		=> 'TAKE-UP:OVERVOLTAGE SUPPLIED TO SERVO AMP.',
	'1412'		=> 'TAKE-UP:SERVO AMP., IPM ERROR',
	'1413'		=> 'SURFACE ROLLER IN FORWARD ROTATION',
	'1414'		=> 'SURFACE ROLLER IN REVERSE ROTATION',
	'1415'		=> 'TAKE-UP:SERVOCOUNTER OVERFLOW',
	'1416'		=> 'TAKE-UP:SERVO AMP. RELEASE ERROR',
	'1417'		=> 'TAKE-UP:SERVO AMP. EMERGENCY-STOP BEING RELEASED',
	'1418'		=> 'TAKE-UP:ABNORMAL SIGNAL FROM ENCORDER',
	'1419'		=> 'TAKE-UP:COMMUNICATION, TIME-OUT ERROR',
	'1420'		=> 'TAKE-UP:COMMUNICATION, SERVO_AMP RECEIVE ERROR',
	'1421'		=> 'TAKE-UP:COMMUNICATION, SERVO_AMP RESPONSE ERROR',
	'1422'		=> 'MAIN CONTROL:FAILURE TO TAKE-UP FOR FELL-FWD SIGNAL',
	'1423'		=> 'TAKE-UP:COMMUNICATION, DIRECTION SIGNAL FAILURE',
	'1450'		=> 'MAIN CONTROL:STOP SIGNAL FROM TAKE-UP(BW)',
	'1470'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM TAKEUP',
	'1471'		=> 'MAIN CONTROL: STOP SIGNAL FROM TAKEUP',
	'1472'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH TAKEUP',
	'1473'		=> 'MAIN CONTROL: SEND ERROR, WITH TAKEUP',
	'1474'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM TAKEUP',
	'1475'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH TAKEUP',
	'1476'		=> 'MAIN CONTROL: FAILURE TO TAKEUP FOR PATTERN CHANGE',
	'1477'		=> 'MAIN CONTROL: FAILURE TO TAKEUP FOR PATTERN SETTING',
	'1478'		=> 'MAIN CONTROL: FAILURE TO TAKEUP FOR STOP MARK SIGNAL',
	'1479'		=> 'MAIN CONTROL: FAILURE TO TAKEUP FOR FELL-FWD SIGNAL',
	'1480'		=> 'MAIN CONTROL: FAILURE TO LET-OFF STATUS IN OPERATION',
	'1490'		=> 'MAIN CONTROL: FAILURE TO LETOFF (option.set)',
	'1491'		=> 'MAIN CONTROL: FAILURE TO LH LETOFF (option.set)',
	'1492'		=> 'MAIN CONTROL: FAILURE TO RH LETOFF (option.set)',
	'1493'		=> 'MAIN CONTROL: FAILURE TO UPPER LETOFF (option.set)',
	'1494'		=> 'MAIN CONTROL: FAILURE TO TAKEUP (option.set)',
	'1495'		=> 'LETOFF: RESET',
	'1496'		=> 'LETOFF(L): RESET',
	'1497'		=> 'LETOFF(R): RESET',
	'1498'		=> 'LETOFF(UPPER): RESET',
	'1499'		=> 'TAKEUP: RESET',
	'1700'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM SC INVERTER',
	'1701'		=> 'MAIN CONTROL: STOP SIGNAL FROM SC INVERTER',
	'1702'		=> 'MAIN CONTROL: COMMUNICATIONS ERROR, WITH SC INVERTER',
	'1703'		=> 'SC INVERTER:OVERHEAT',
	'1704'		=> 'SC INVERTER:OVERCURRENT',
	'1705'		=> 'SC INVERTER:OVERVOLTAGE',
	'1706'		=> 'SC INVERTER:LOW VOLTAGE',
	'1707'		=> 'SC INVERTER:MAIN MOTOR REVOLUTION ERROR',
	'1708'		=> 'SC INVERTER:MAIN MOTOR REVOLUTION ERROR',
	'1709'		=> 'SC INVERTER:EMERGENCY STOP SIGNAL FROM MAIN CONTROL',
	'1710'		=> 'SC INVERTER:IPM ERROR',
	'1711'		=> 'SC INVERTER:PROGRAM REWRITABLE STATE',
	'1712'		=> 'SC INVERTER:FAILURE OF PROGRAM WRITING',
	'1800'		=> 'DOBBY: ABNORMAL OIL PUMP',
	'1801'		=> 'DOBBY: ABNORMAL SIGNALLING FM PROXIMITY SWITCHES',
	'1802'		=> 'DOBBY: INVERSION PROHIBITED FM FWD TO REVERSE',
	'1803'		=> 'DOBBY: INVERSION PROHIBITED FM REVERSE TO FWD',
	'1804'		=> 'DOBBY: INCHING IN UNINVERTIBLE-ANGLE RANGE (FM FWD TO REVERSE)',
	'1805'		=> 'DOBBY: INCHING IN UNINVERTIBLE-ANGLE RANGE (FM REVERSE TO FWD)',
	'1806'		=> 'DOBBY: NO.01 SOLENOID BREAK',
	'1807'		=> 'DOBBY: NO.02 SOLENOID BREAK',
	'1808'		=> 'DOBBY: NO.03 SOLENOID BREAK',
	'1809'		=> 'DOBBY: NO.04 SOLENOID BREAK',
	'1810'		=> 'DOBBY: NO.05 SOLENOID BREAK',
	'1811'		=> 'DOBBY: NO.06 SOLENOID BREAK',
	'1812'		=> 'DOBBY: NO.07 SOLENOID BREAK',
	'1813'		=> 'DOBBY: NO.08 SOLENOID BREAK',
	'1814'		=> 'DOBBY: NO.09 SOLENOID BREAK',
	'1815'		=> 'DOBBY: NO.10 SOLENOID BREAK',
	'1816'		=> 'DOBBY: NO.11 SOLENOID BREAK',
	'1817'		=> 'DOBBY: NO.12 SOLENOID BREAK',
	'1818'		=> 'DOBBY: NO.13 SOLENOID BREAK',
	'1819'		=> 'DOBBY: NO.14 SOLENOID BREAK',
	'1820'		=> 'DOBBY: NO.15 SOLENOID BREAK',
	'1821'		=> 'DOBBY: NO.16 SOLENOID BREAK',
	'1822'		=> 'DOBBY: NO.17 SOLENOID BREAK',
	'1823'		=> 'DOBBY: NO.18 SOLENOID BREAK',
	'1824'		=> 'DOBBY: NO.19 SOLENOID BREAK',
	'1825'		=> 'DOBBY: NO.20 SOLENOID BREAK',
	'2000'		=> 'MAIN CONTROL:LENO, ABNORMAL DATA',
	'2001'		=> 'MAIN CONTROL:LENO(R) ALARM SIGNAL INPUT',
	'2002'		=> 'MAIN CONTROL:LENO(L) ALARM SIGNAL INPUT',
	'2003'		=> 'MAIN CONTROL:LENO(R) FAILED TO DETECT ORIGIN',
	'2004'		=> 'MAIN CONTROL:LENO(L) FAILED TO DETECT ORIGIN',
	'2005'		=> 'MAIN CONTROL:LENO(R) SERVO AMP. OVERCURRENT',
	'2006'		=> 'MAIN CONTROL:LENO(L) SERVO AMP. OVERCURRENT',
	'2102'		=> 'MAIN CONTROL:ABNORMAL PATTERN',
	'2103'		=> 'MAIN CONTROL:ABNORMAL COLOR',
	'2104'		=> 'MAIN CONTROL:ABNORMAL DENSITY',
	'2105'		=> 'MAIN CONTROL:ABNORMAL PILE DATA',
	'2106'		=> 'MAIN CONTROL:ABNORMAL SHEDDING PATTERN',
	'2112'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL',
	'2113'		=> 'YARN TAIL END SENSOR IS ABNORMAL (WIRE BREAK)',
	'2114'		=> 'OPERATE YARN TAIL HANDLING MANUALLY',
	'2115'		=> 'TAIL END SENSOR ARE OFF',
	'2116'		=> 'YARN TAIL END SENSOR: WIRE BREAK(COLOR 1)',
	'2117'		=> 'YARN TAIL END SENSOR: WIRE BREAK(COLOR 2)',
	'2118'		=> 'YARN TAIL END SENSOR: WIRE BREAK(COLOR 3)',
	'2119'		=> 'YARN TAIL END SENSOR: WIRE BREAK(COLOR 4)',
	'2120'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL(COLOR 1)',
	'2121'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL(COLOR 2)',
	'2122'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL(COLOR 3)',
	'2123'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL(COLOR 4)',
	'2170'		=> 'MONITORING STOP NOW',

	######## End of Data ########

	'OTHER_STOP'	=> 'PARAGEM DE OUTRO'	);
}

###################################################################################################
1;
