###################################################################################################
#
# str_zh-tw.pm
#
###################################################################################################

use strict;

###################################################################################################

sub load_str
{
  return (

	######## common.pm ########

	'MENU'					=> '菜單',
	'SUBMENU'				=> '子菜單',
	'BACK'					=> '返回',
	'NOW_EXCEL_IS_BOOTING'			=> 'Excel起動中',
	'NO_DATA_FOUND'				=> '沒有數據',
	'NO_DATA_FOUND_IN_THIS_CONDITION'	=> '沒有與指定條件相符的數據',

	######## Main Menu ########

	'MAIN_MENU'			=> '主菜單',
	'SHIFT_REPORT'			=> '輪班報告',
	'OPERATOR_REPORT'		=> '操作員報告',
	'STYLE_REPORT'			=> '品種報告',
	'PRODUCTION_GRAPH'		=> '生產量圖表',
	'EFFICIENCY_GRAPH'		=> '運轉效率圖表',
	'STATUS_HISTORY'		=> '運轉情況履歷',
	'STOP_ANALYSIS_GRAPH'		=> '停止原因分析圖表',
	'YARN_INVENTORY_FORECAST'	=> '上機一覽和預測',
	'STOP_HISTORY'			=> '停機履歷',
	'DATA_COLLECTION_NETWORK'	=> '數據收集(聯網)',
	'DATA_IMPORT_MEMCARD'		=> '數據導入(存儲記憶卡)',
	'LINK_TO_LOOM_SCREEN'		=> '連接到幾台畫面',
	'REPORT_SETTING'		=> '報告設定',
	'IP_ADDRESS_SETTING'		=> 'IP地址設定',
	'PASSWORD_SETTING'		=> '密碼設定',
	'SHIFT_DATA'			=> '輪班紀錄',
	'OPERATOR_DATA'			=> '操作員紀錄',
	'LOOM_DATA'			=> '機台記錄',
	'SETTING'			=> '設定',
	'DATA_EDIT'			=> '數據編輯',
	'DATA_EDIT_MENU'		=> '數據編輯子菜單',
	'EXPORT_CSV_FILE'		=> '導出至CSV文件',

	######## Shift data & Operator data ########

	'SELECT_BY_LOOM'		=> '選擇機台',
	'SELECT_BY_STYLE'		=> '選擇品種',
	'OPERATOR'			=> '操作員',
	'PERIOD'			=> '期間',
	'SELECT_ALL'			=> '全選',
	'SHOW_GRAPH'			=> '顯示圖表',
	'SHOW_REPORT'			=> '顯示報告',

	######## Setting ########

	'RESET_MODEIFY'				=> '回復至初始狀態',
	'ENTER'					=> '執行',
	'PLEASE_CHECK_COLOR_NUM'		=> '選擇顏色號碼',
	'PLEASE_INPUT_NUMBER'			=> '請輸入數字',
	'IP_NUMBER_MUST_BE_BETWEEN_0_AND_255'	=> 'IP地址的數字可在0～255的範圍內選擇',
	'DELETE'				=> '刪除',
	'RANGE_OF_IP_ADDRESS'			=> 'IP地址的範圍',
	'SETTING_RESULT'			=> '設定結果',
	'SETTING_SUCCEED'			=> '設定成功\',    # '
	'NO_VALID_DATA_FOUND'			=> '沒有有效的數據',
	'APPLY_CHANGE_TO_DATA'			=> '將變更反映至存儲數據中',
	'OK'					=> '確定',

	'PASSWORD_IS_TOO_SHORT'		=> '密碼數不足',
	'NEED_6_CHARACTERS_OR_MORE'	=> '需要6位文字以上',
	'CANT_USE_SPACE_FOR_PASSWORD'	=> '密碼中不能有空白',
	'THE_PASSWORDS_DO_NOT_MATCH'	=> '密碼不一緻',
	'DISABLE_PASSWORD'		=> '密碼設定為無效',
	'ENABLE_PASSWORD'		=> '密碼設定為有效',
	'USERNAME'			=> '用戶名',
	'NEW_PASSWORD'			=> '新密碼',
	'CONFIRM_NEW_PASSWORD'		=> '新密碼(確認)',
	'PASSWORD_ERROR'		=> '密碼不正確',
	'PASSWORD_TARGET_AREA'		=> '密碼有效範圍',

	'PICK'				=> '投緯次數',
	'METER'				=> '米',
	'YARD'				=> '碼',

	'WARP_TOP_MISS'			=> '經紗(上)',
	'WARP_MISS'			=> '經紗',
	'FALSE_SELVAGE_MISS'		=> '廢邊紗',
	'LENO_L_MISS'			=> '紗羅邊(左)',
	'LENO_R_MISS'			=> '紗羅邊(右)',
	'WEFT_MISS'			=> '缺緯',
	'WARP_OUT'			=> '了機',
	'CLOTH_DOFFING'			=> '落布',
	'MANUAL_STOP'			=> '手動',
	'POWER_OFF'			=> '電源切斷',
	'OTHER_STOP'			=> '其他',

	'WF1'				=> 'WF1',
	'WF2'				=> 'WF2',
	'LH'				=> 'LH',

	'COLOR1'			=> '顏色1',
	'COLOR2'			=> '顏色2',
	'COLOR3'			=> '顏色3',
	'COLOR4'			=> '顏色4',
	'COLOR5'			=> '顏色5',
	'COLOR6'			=> '顏色6',

	'STOP_CAUSE'			=> '停止原因',
#	'DETAIL_OF_WEFT_STOP'		=> '缺緯詳細內容',
	'UNIT'				=> '單位',
	'START_OF_WEEK'			=> '一周的開始',
	'CONDITION_OF_TOTALING'		=> '統計的條件',

	'BEAM_TYPE'			=> '經軸種類',
	'SINGLE_BEAM'			=> '單經軸',
	'DOUBLE_BEAM'			=> '雙經軸',

	'SHIFT'				=> '班',
	'DATE'				=> '日期',
	'WEEK'				=> '周',
	'MONTH'				=> '月',

	'SUNDAY'			=> '星期天',
	'MONDAY'			=> '星期一',
	'TUESDAY'			=> '星期二',
	'WEDNESDAY'			=> '星期三',
	'THURSDAY'			=> '星期四',
	'FRIDAY'			=> '星期五',
	'SATDAY'			=> '星期六',

	'EFFICIENCY'			=> '運轉效率',
	'RUN_TIME'			=> '運轉時間',
	'PERCENT_OVER'			=> '％以上',
	'MINUITE_OVER'			=> '分鐘以上',

	'REPORT_ITEM'			=> '報告項目',
	'TOP_BEAM_NAME'			=> '經紗名(上)',
	'BEAM_NAME'			=> '經紗名',
	'RPM'				=> '轉╱分鐘',
	'STOP_TIME'			=> '停止時間',
	'PRODUCTION'			=> '生產量',

	'PERMISSION_DENY'				=> '無許可',
	'CANT_ACCESS_THIS_PAGE_FROM_REMOTE'		=> '無法遙控進入此頁面',
	'DISABLE_PASSWORD_FORCIBLY'			=> '強制地消除密碼',
	'ARE_YOU_SURE_YOU_WANT_TO_DISABLE_PASSWORD'	=> '你確定是要消除密碼嗎？',
	'PASSWORD_IS_DISABLED'				=> '密碼已無效',

	'LANGUAGE_SETTING'		=> '語言設定',

	######## Loom data ########

	'CANCEL_DATA_COLLECTING'	=> '中止數據收集',
	'CLOSE'				=> '關閉',
	'DATA_COLLECTING_IS_CANCELED'	=> '數據收集被中止',
	'SUCCEED'			=> '成功\',    # '
	'START_DATA_COLLECTING'		=> '數據收集開始',
	'END_DATA_COLLECTING'		=> '數據收集結束',
	'NO_DATA_COLLECTED'		=> '未收集到數據',
	'START_DATA_CONVERTING'		=> '數據轉換開始',
	'COMPLETED_ALL_PROPERLY'	=> '全部正常結束',
	'PHASE'				=> '階段',
	'DONE'				=> '結束',
	'LOOM_CLOCK_IS_WRONG'		=> '機台的顯示時間不准',

	'LOOM_CLOCK_SETTING'			=> '設定機台的顯示時間',
	'TARGET_DATE'				=> '設定日期',
	'CANCEL_LOOM_CLOCK_SETTING'		=> '中斷設定時間',
	'START_LOOM_CLOCK_SETTING'		=> '開始設定時間',
	'LOOM_CLOCK_SETTING_IS_CANCELED'	=> '時間設定被中斷',
	'END_LOOM_CLOCK_SETTING'		=> '時間設定已完成',
	'SET_CLOCK'				=> '時間設定',
	'NOT_NEED_ADJUST'			=> '無需修正',
	'TIME_DIFFERENCE'			=> '時間偏差',

	'SEC'		=> '秒',
	'MINUITE'	=> '分鐘',
	'HOUR'		=> '小時',
	'DAY'		=> '日',
	'YEAR'		=> '年',

#	'PARENT_FOLDER'			=> '文件夾',
#	'BACK_TO_PREV_FOLDER'		=> '返回上一個文件夾',
	'CANNOT_ACCESS_THIS_FOLDER'	=> '無法打開此文件夾',
	'CANNOT_FIND_THIS_FOLDER'	=> '無此文件夾',
	'NO_FILES'			=> '無此文件',
#	'NO_SUB_FOLDERS'		=> '無子文件夾',
	'CURRENT_FOLDER'		=> '當前文件夾',
#	'MOVE_TO_SUB_FOLDER'		=> '移動至子文件夾',
#	'MOVE_TO_THIS_FOLDER'		=> '移動至此文件夾',
#	'SUB_FOLDER_LIST'		=> '子文件夾一覽',
	'FILE_LIST'			=> '文件一覽',
	'IMPORT_SELECTED_FILES'		=> '導入被選擇的文件',

	'START_DATA_CHECKING'		=> '開始數據檢查',
	'FUTURE_DATA' 			=> '機器內設定的日期為將來',
	'TOO_OLD_DATA'			=> '機器內設定的日期為過去',
	'CANT_READ_FILE'		=> '文件無法讀取',
	'DATA_ERROR'			=> '數據錯誤',
	'NOT_TMS_DATA'			=> '非TMS格式文件',
	'THERE_IS_NO_VALID_DATA'	=> '無有效數據',

	'SHOW_STYLE_LIST'		=> '品種履歷的顯示',
	'STYLE_NAME'			=> '品種名稱',
	'SET_STYLE'			=> '設定品種名稱',
	'LOOM_NAME'			=> '機台名稱',
	'CURRENT_LOOM_NAME'		=> '當前機台名稱',
	'NEW_LOOM_NAME'			=> '新機台名稱',
	'CHANGE_LOOM_NAME'		=> '更改機台名稱',
	'CHANGE_SELECT_LOOM_NAME_OK'	=> '你確定是要變更被選擇的機台名稱嗎？',
	'CHANGEING_DATA'		=> '正在進行數據變更',
	'DELETE_DATA'			=> '數據刪除',
	'DELETE_SELECT_DATA_OK'		=> '你確定是要刪除被選擇的數據嗎？',
	'DELETING_DATA'			=> '正在進行數據刪除',
	'SELECT_EXPORT_DATA'		=> '請選擇導出數據',
	'EXPORT_DATA'			=> '數據導出',
	'EXPORT_DONE'			=> '導出完成',
	'SAVE_FOLDER'			=> '保存至文件夾',
	'REPORT_DATA_RESTRUCTION'	=> '報告數據再建',

	'DATA_IS_UNDER_UPDATING'	=> '正在更新數據',
	'OPERATION_OVERLAPED'		=> '操作重復',
	'BE_IN_USE_BY_OTHER_USER'	=> '其它的用戶正在執行此項操作',
	'TRY_AGAIN_AFTER_A_WHILE'	=> '請稍后再試',
	'USING_USER'			=> '正在使用的用戶',
	'LOCAL_USER'			=> '當地用戶',
	'REMOTE_USER'			=> '遠程用戶',

	'NOT_RESTRUCTION'		=> '數據未再建',
	'NEED_RESTRUCTION_FIRST'	=> '請先進行數據再建',
	'KEEP_GOING'			=> '繼續',

	######## IP Table ########

	'CANCEL_PROCESSING'		=> '處理的中斷',
	'NO_NAME'			=> '無名稱',
	'NO_LOOM_SELECTED'		=> '機台未被選擇',

	'CREATE_IP_TABLE'		=> '新增IP表格',
	'IPTABLE_INPUT_IP_MSG'		=> '在功能表中輸入追加的機台IP位址',
	'IPTABLE_INPUT_NAME_MSG'	=> '在功能表中輸入追加的機台名稱',
	'IPTABLE_SELECT_ITEM_MSG'	=> '在功能表中選擇追加的軟體',
	'IPTABLE_DATA_CONFIRM_MSG'	=> '按以下條件設置功能表',
	'IPTABLE_DUPLICATE_MSG'		=> '在下一組中輸入的資料重復',
	'PLEASE_INPUT_0_255_NUMBER'	=> '輸入0～255的數位',
	'PLEASE_INPUT_000_999_NUMBER'	=> '輸入0～999的數位',
	'PLEASE_INPUT_IP_ADDRESS'	=> '輸入IP地址',
	'GROUP'				=> '組',
	'DOWNLOAD_IP_TABLE_DATA'	=> 'IP表格的資料下載',

	'STYLE_MANAGER'			=> '格調管理器',
	'PATTERN_MANAGER'		=> '圖案管理器',
	'PARTS_CATALOG'			=> '部件目錄',
	'EFFICIENCY_BOARD'		=> '生產率顯示板',
	'WEB_CAMERA'			=> 'Web照相機',

	'PAGE_1'			=> '第1頁',
	'PAGE_2'			=> '第2頁',
	'PAGE_3'			=> '第3頁',
	'NEXT'				=> '下  頁',
	'CREATE_FILE'			=> '新建文檔',
	'DOWNLOAD_FILE'			=> '文檔的下載',

	'SEND_IP_TABLE_TO_MACHINES'	=> '發送IP表格',
	'CANCEL_SEND_DATA'		=> '資料傳輸中斷',
	'START_SEND_DATA'		=> '資料傳輸開始',
	'SEND_DATA_IS_CANCELED'		=> '資料傳輸被中斷',
	'END_SEND_DATA'			=> '資料傳輸完成',

	'IP_TABLE_VERSION_CHECK'	=> 'IP表格的版本確認',
	'CANCEL_VERSION_CHECK'		=> '版本確認中斷',
	'START_VERSION_CHECK'		=> '版本確認開始',
	'VERSION_CHECK_IS_CANCELED'	=> '版本確認被中斷',
	'END_VERSION_CHECK'		=> '版本確認完成',
	'HOST_IP_TABLE_VERSION'		=> '主机的IP表格版本',
	'LOOM_IP_TABLE_VERSION'		=> '織機的IP表格版本',

	######## For Service TMS ########

	'SERVICE_REPORT'		=> 'Service Report Data',
#	'IMPORT_SERVICE_MEMCARD'	=> 'Import Data (for Service)',
#	'LOG_MESSAGE_TRANSLATION'	=> 'Log Message Translation',
	'SWITCH_USE_DATA'		=> 'Switch Using Data',
	'SWITCH_DATA'			=> 'Switch Data',
	'CURRENT_USE_DATA'		=> 'Current Use Data',
	'NOT_EXIST'			=> 'Not Exist',
	'SELECT_SWITCH_DATA'		=> 'Select Switch Data',
	'EXEC_SWITCH_DATA'		=> 'Exec Switch',
	'RENAME_DATA'			=> 'Rename Data',
	'NEW_NAME'			=> 'New Name',
	'SELECT_RENAME_DATA'		=> 'Select Rename Data',
	'EXEC_RENAME_DATA'		=> 'Exec Rename',
	'CREATE_DATA'			=> 'Create New Data Area',
	'CREATE_NAME'			=> 'New Name',
	'EXEC_CREATE_DATA'		=> 'Exec Create',
	'SELECT_DELETE_DATA'		=> 'Select Delete Data',
	'EXEC_DELETE_DATA'		=> 'Exec Delete',
	'PLEASE_SELECT_DATA'		=> 'Please Select Data.',
	'PLEASE_INPUT_NAME'		=> 'Please Input Name.',
	'DUPLICATE_NAME'		=> 'Duplicate Name, Change Input Name.',
	'INPUT_DATA_FILE_NAME'		=> 'Input Data File Name',

	######## For TMS Scanner ########

	'CLOTH_BEAM_LIST_SETTING'	=> '卷布經軸一覽設定',	#1
	'OTHER_LIST_SETTING'		=> '其他一覽設定',
	'CLOTH_BEAM_MAINTENANCE'	=> '卷布經軸維護',
	'SCANNER_SETTING'		=> '掃描器設定',
	'STYLE_SETTING'			=> '品種設定',
	'SHIFT_SCHEDULE_SETTING'	=> '輪班日程設定',
	'UNIT_SETTING'			=> '單位設定',
	'LOOM_NAME_SPEC_SETTING'	=> '機器名稱和規格的設定',
	'OPERATION_STATUS' 		=> '運轉狀態顯示',

#	'JAT710_IP_ADDRESS'		=> 'JAT710的IP地址',	#34
#	'JAT710_MEMORY_CARD'		=> 'JAT710的存儲卡',	#35
	'COLLECT_DATA_USING_MEMORY_CARD' => '用存儲卡收集資料',	#36
	'SCANNER_IP_ADDRESS'		=> '掃描器的IP地址',	#37
	'IP_ADDRESS'			=> 'IP地址',		#38

	'UPDATE_SETTING'	=> '更新設定',	#10

	'INVALID_INPUT_VALUE'	=> '輸入值不正確',	#26
	'ALPHANUMERIC_ONLY'	=> '僅限英文字元',	#28
	'UPDATE_OK'		=> '可以更新嗎',	#iTTCS

	'SCANNER'		=> '掃描器',	#11
	'YES'			=> '是',	#29
	'NO'			=> '否',	#30
	'PAGE'			=> '頁',	#20
	'REFRESH'		=> '更新顯示',	#76

	'LENGTH_UNIT'		=> '長度單位',	#52
	'DENSITY_UNIT'		=> '密度單位',	#53

	'STATUS'		=> '狀態',	#68
	'DURATION'		=> '持續時間',	#69
	'STOP_COUNT'		=> '停車次數',	#70
	'EFFICIENCY'		=> '運轉率',	#71
	'CURRENT_SHIFT'		=> '現在位移',	#72
	'DOFFING_FORECAST'	=> '落布預測',	#73
	'WARP_OUT_FORECAST'	=> '了機預測',	#74
	'HH_MM'			=> '小時:分',	#75
	'LOWER'			=> '下',	#55,56,57
	'UPPER'			=> '上',

	'DENSITY'		=> '密度',	#43
	'DOFF_LENGTH'		=> '落布長度',	#44
	'SHRINKAGE'		=> '收縮率',		#54
	'UPPER_BEAM'		=> '上經軸',		#55
	'LOWER_BEAM'		=> '下經軸',		#56
	'BEAM'			=> '經軸',		#57
	'SET_LENGTH'		=> '設定長度',		#58
	'USE_EACH_DOFF_LENGTH'	=> '分別設定落布長度',	#59
	'CLOTH'			=> '交叉',		#60
	'CLOTH_LENGTH'		=> '交叉長度',		#61
	'BEAM_REMAIN'		=> '剩餘經紗長度',	#62
	'CORRECT_CLOTH_LENGTH'	=> '修正交叉長度',	#63
	'CORRECT_BEAM_REMAIN'	=> '修正剩餘經紗長度',	#64
	'FORECAST_EFFICIENCY'	=> '預測運轉率',		#65
	'CLOTH_LENGTH_CORRECTION' => '交叉長度修正係數',	#66

	'LOOM_ID'		=> '机器ID',	#39
	'SET_TO_ALL'		=> '全部適用',	#40

	'SHIFT_SCHEDULE'	=> '輪班日程',	#48
	'SIMPLE_SETTING'	=> '簡單設定',	#49
	'DETAIL_SETTING'	=> '詳細設定',	#50
	'SHIFT_NUMBER'		=> '輪班數',	#51

	'OPST__RUN'		=> '運行中',	#77
	'OPST__OUT_OF_PRODUCT'	=> '非作業對象',
	'OPST__WARP_OUT'	=> '了機',
	'OPST__CLOTH_DOFFING'	=> '落布',
	'OPST__MACHINE_FAILURE'	=> '呼叫(故障)',
	'OPST__CLOTH_MENDING'	=> '呼叫(布疵)',
	'OPST__POWER_OFF'	=> '電源切斷',
	'OPST__WARP_TOP'	=> '經紗(上)',
	'OPST__WARP'		=> '經紗',
	'OPST__FALSE_SELVAGE'	=> '廢邊紗',
	'OPST__CC_FRONT'	=> '廢邊紗(前)',
	'OPST__CC_REAR'		=> '廢邊紗(後)',
	'OPST__LENO_L'		=> '紗羅邊(左)',
	'OPST__LENO_R'		=> '紗羅邊(右)',
	'OPST__WEFT'		=> '緯紗',
	'OPST__MANUAL'		=> '手動',
	'OPST__OTHER'		=> '其他',		#91
	'OPST__COMM_ERR'	=> '通信錯誤',		#92
	'OPST__DATA_ERR'	=> '資料錯誤',		#93
	'OPST__NOT_SUPPORT'	=> '機台未回應',	#94

 	'PER_CM'		=> '/cm',
	'PER_INCH'		=> '/inch',

	'ERROR'			=> '錯誤',	#12
	'DUPLICATE_MAC_NAME'	=> '以下的機台名稱重複',	#41
	'DUPLICATE_STYLE_NAME'	=> '以下的品種名稱重複',	#46
	'BACK_TO_SETTING'	=> '返回設定畫面',		#32

	'SCANNER_UPLOAD_ERROR'		=> '未能更新掃描器的設定',	#13
	'SCANNER_COMM_ERROR'		=> '未能與掃描器進行通信',	#14
	'THIS_IP_IS_NOT_SCANNER1'	=> '以下的設定值非掃描器1的IP地址',	#15
	'SCANNER_CONFIG_ERROR'		=> '掃描器結構不正確',		#16
	'CHECK_SCANNER_CONFIG'		=> '請確認各掃描器的設定',	#17
	'SCANNER_IS_NOT_RUN'		=> '掃描器未起動',		#19

	######## For LWT ########

	'DETAIL_OF_STOP_CAUSE'	=> '停止原因詳細內容',
	'CC_FRONT_MISS'		=> '廢邊紗(前)',
	'CC_REAR_MISS'		=> '廢邊紗(後)',
	'LENO_MISS'		=> '紗羅邊',

	'LOOM_IP_ADDRESS'	=> '機台的IP地址',
	'USE_OF_MEMORY_CARD'	=> '使用記憶卡',

	'OTHER_SETTING'				=> '其他的設定',
	'DATA_COLLECTION_WARNING_TIME'		=> '數據收集警告時間',
	'DATA_IS_NOT_COLLECTED_FOR_A_WHILE'	=> '暫時不執行數據收集',
	'MOVE_TO_DATA_COLLECTION'		=> '移動到 [數據收集] 頁',
	'IS_DATA_COLLECTED_FIRST'		=> '先執行數據收集嗎 ?',

	######## For Vista ########

	'DOWNLOAD_TMS_HELPER'	=> 'TMS Helper 的下載',

	######## New Memory Card Data Read 2008/03/31 ########

	'REGISTERED_FOLDER'	=> 'Registered Folder',
	'REGISTER'		=> 'Register',
	'UNREGISTER'		=> 'Unregister',

	######## End of Data ########

	'END_OF_DATA'			=> 'END_OF_DATA'	);
}

###################################################################################################
# Stop Cause Strings
###################################################################################################

sub load_stop_cause_str_jat710
{
  return (

	'0000'		=> '經紗斷紗停車',
	'0001'		=> '棄邊紗斷裂停車',
	'0002'		=> '右紗羅邊破裂停車',
	'0003'		=> '左紗羅邊破裂停車',
	'0004'		=> '緯紗WF1錯誤停車( 第1梭/ 色 )',
	'0005'		=> '緯紗WF1錯誤停車( 第2梭/ 色 )',
	'0006'		=> '緯紗WF1錯誤停車( 第3梭/ 色 )',
	'0007'		=> '緯紗WF1錯誤停車( 第4梭/ 色 )',
	'0008'		=> '緯紗WF1錯誤停車( 第5梭/ 色 )',
	'0009'		=> '緯紗WF1錯誤停車( 第6梭/ 色 )',
	'0010'		=> '緯紗WF2錯誤停車( 第1梭/ 色 )',
	'0011'		=> '緯紗WF2錯誤停車( 第2梭/ 色 )',
	'0012'		=> '緯紗WF2錯誤停車( 第3梭/ 色 )',
	'0013'		=> '緯紗WF2錯誤停車( 第4梭/ 色 )',
	'0014'		=> '緯紗WF2錯誤停車( 第5梭/ 色 )',
	'0015'		=> '緯紗WF2錯誤停車( 第6梭/ 色 )',
	'0016'		=> '緯紗供給錯誤停車  ( 第1梭/ 色 )',
	'0017'		=> '緯紗供給錯誤停車  ( 第2梭/ 色 )',
	'0018'		=> '緯紗供給錯誤停車  ( 第3梭/ 色 )',
	'0019'		=> '緯紗供給錯誤停車  ( 第4梭/ 色 )',
	'0020'		=> '緯紗供給錯誤停車  ( 第5梭/ 色 )',
	'0021'		=> '緯紗供給錯誤停車  ( 第6梭/ 色 )',
	'0025'		=> '落卷停車',
	'0027'		=> '停車SW [STOP] 被按下',
	'0028'		=> '緊急停車SW被按下',
	'1502'		=> 'TAPO: 不能處理( 無錯誤紗 )',
	'1503'		=> 'TAPO: 處理失敗( 錯誤紗太短 )',
	'1504'		=> 'TAPO: 處理失敗( 錯誤紗太長 )',
	'2101'		=> '遙控: 停止',
	'2150'		=> '特別表示( 故障 )',
	'2151'		=> '特別表示( 疵 )',
	'2153'		=> '特別表示( 了機 )',
	'2154'		=> '特別表示( 落卷 )',
	'2155'		=> '特別表示( 呼叫 )',
	'2414'		=> '經紗斷而停止( 普通織物 )',
	'2415'		=> '經紗斷而停止( 毛圈 )',
	'2420'		=> '落布停止(枚數)',
	'2421'		=> '卷布輥被落卷( 毛邊停止 )',
	'2422'		=> '卷布輥被落卷( 折布停止 )',
	'2430'		=> '卷布輥落卷(批量計數終了)',

	'0023'		=> '棄邊紗捲撓到捲取羅拉上',
	'0024'		=> '織口安全裝置動作',
	'0026'		=> '落卷信號',
	'0031'		=> '中紗羅邊破裂停車',
	'0032'		=> '織口安全裝置的故障',
	'0101'		=> '加油成功\',    # '
	'0102'		=> '加油失敗',
	'0103'		=> '主控制: 設定值初期化',
	'0105'		=> '請安裝右側手轉盤蓋\',    # '
	'0108'		=> '設定為使用正轉寸動緯紗',
	'0110'		=> '設定為不使用探緯針1',
	'0111'		=> '調整為多臂動作方式',
	'0112'		=> '整平﹕動作異常',
	'0113'		=> '由於整平而啟動聯鎖',
	'0114'		=> '整平﹕複位異常',
	'0115'		=> '整平﹕由停止開關中斷',
	'0116'		=> '給油傳感器檢測到異常( 開口裝置 )',
	'0117'		=> '給油中( 給油閥複位中 )',
	'0118'		=> '給油失敗( 給油壓力不升高 )',
	'0119'		=> '給油失敗( 給油壓力不下降 )',
	'0120'		=> '自動水平測量: 超時錯誤',
	'0121'		=> '自動水平測量: 感測器輸入異常',
	'0122'		=> '油泵異常( 開口裝置 )',
	'0123'		=> '經  傳感器  OFF',
	'0124'		=> '廢棄布邊  傳感器  OFF',
	'0125'		=> '傳感器  OFF',
	'0126'		=> '設定為不使用探緯針1',
	'0127'		=> '設定為不使用探緯針2',
	'0128'		=> '設定為不使用圈數探測器',
	'0129'		=> '吹風機馬達溫度  OFF',
	'0130'		=> '閃光儀  ON',
	'0131'		=> '演示停車',
	'0132'		=> '請按[1捲解除]-SW',
	'0133'		=> '經  傳感器  OFF(下)',
	'0134'		=> '經  傳感器  OFF(上)',
	'0135'		=> 'WF1 SIGNALS LESS',
	'0136'		=> '織口安全裝置  OFF',
	'0200'		=> '起動SW [START] 的故障',
	'0201'		=> '停車SW [STOP] 的故障',
	'0202'		=> '逆轉SW [REVERSE] 的故障',
	'0203'		=> '正轉SW [FORWORD] 的故障',
	'0204'		=> '連鎖SW [INTER  LOCK] 的故障',
	'0205'		=> '兩手按SW的故障',
	'0206'		=> '剎車器解除SW的故障',
	'0207'		=> '剎車器電壓  不良',
	'0210'		=> '主馬達  過負載',
	'0211'		=> '140V  電源異常',
	'0212'		=> '24V1  電源異常',
	'0213'		=> '24V2  電源異常',
	'0214'		=> '24V4  電源異常',
	'0215'		=> '48V  電源異常',
	'0216'		=> '15V  電源異常',
	'0217'		=> 'P15V  電源異常',
	'0218'		=> 'M15V  電源異常',
	'0219'		=> '12V  電源異常',
	'0220'		=> '5V  電源異常',
	'0221'		=> '探經座接頭脫落',
	'0222'		=> '主馬達過熱',
	'0223'		=> '編碼器  Z相  異常',
	'0224'		=> '編碼器  A相·B相  異常',
	'0225'		=> '主控制: 電池電壓低下',
	'0226'		=> '吹風馬達不可運轉',
	'0227'		=> '安全傳感器的故障',
	'0228'		=> '熱剪刀裝置的異常',
	'0229'		=> '剎車器電壓  不良 ( 運轉中 )',
	'0280'		=> 'CPU電路板的故障',
	'0281'		=> 'ETHERNET CH0 異常',
	'0282'		=> 'ETHERNET CH1 異常',
	'0300'		=> '變頻器異常或寸動負載過重',
	'0301'		=> '剎車器力矩不足',
	'0302'		=> '探緯器( WF1 )  異常檢出',
	'0303'		=> '探緯器( WF2 )  異常檢出',
	'0304'		=> '無編碼器Z相的輸入信號( 運轉中 )',
	'0305'		=> '有編碼器逆轉脈衝的輸入信號( 運轉中 )',
	'0306'		=> '編碼器正轉脈衝計數器異常( 運轉中 )',
	'0307'		=> '圈數探測器  異常檢出',
	'0308'		=> '圈數探測器信號數過多    第1梭/ 色',
	'0309'		=> '圈數探測器信號數過多    第2梭/ 色',
	'0310'		=> '圈數探測器信號數過多    第3梭/ 色',
	'0311'		=> '圈數探測器信號數過多    第4梭/ 色',
	'0312'		=> '圈數探測器信號數過多    第5梭/ 色',
	'0313'		=> '圈數探測器信號數過多    第6梭/ 色',
	'0314'		=> '圈數探測器信號數過少    第1梭/ 色',
	'0315'		=> '圈數探測器信號數過少    第2梭/ 色',
	'0316'		=> '圈數探測器信號數過少    第3梭/ 色',
	'0317'		=> '圈數探測器信號數過少    第4梭/ 色',
	'0318'		=> '圈數探測器信號數過少    第5梭/ 色',
	'0319'		=> '圈數探測器信號數過少    第6梭/ 色',
	'0320'		=> 'ABS: 起源查出失敗 (第1梭/色)',
	'0321'		=> 'ABS: 起源查出失敗 (第2梭/色)',
	'0322'		=> 'ABS: 起源查出失敗 (第3梭/色)',
	'0323'		=> 'ABS: 起源查出失敗 (第4梭/色)',
	'0324'		=> 'ABS: 起源查出失敗 (第5梭/色)',
	'0325'		=> 'ABS: 起源查出失敗 (第6梭/色)',
	'0326'		=> 'ABS: 運轉中動作異常 (第1梭/色)',
	'0327'		=> 'ABS: 運轉中動作異常 (第2梭/色)',
	'0328'		=> 'ABS: 運轉中動作異常 (第3梭/色)',
	'0329'		=> 'ABS: 運轉中動作異常 (第4梭/色)',
	'0330'		=> 'ABS: 運轉中動作異常 (第5梭/色)',
	'0331'		=> 'ABS: 運轉中動作異常 (第6梭/色)',
	'0332'		=> 'ABS: 發生報警 (第1梭/色)',
	'0333'		=> 'ABS: 發生報警 (第2梭/色)',
	'0334'		=> 'ABS: 發生報警 (第3梭/色)',
	'0335'		=> 'ABS: 發生報警 (第4梭/色)',
	'0336'		=> 'ABS: 發生報警 (第5梭/色)',
	'0337'		=> 'ABS: 發生報警 (第6梭/色)',
	'0403'		=> '主控制: 數據通訊異常( SOMIC  ch0 )',
	'0404'		=> '主控制: 數據通訊異常( SOMIC  ch1 )',
	'0405'		=> '停電停止',
	'0500'		=> '請更換LH剪刀',
	'0501'		=> '請手動加油',
	'0502'		=> '請手動加油  齒輪箱',
	'0503'		=> '請手動加油  送經裝置',
	'0504'		=> '請手動加油  開口裝置',
	'1000'		=> '主控制: 送經裝置來的緊急停車信號',
	'1001'		=> '主控制: 收到送經裝置來的停車命令',
	'1002'		=> '主控制: 向送經裝置的發出超時錯誤',
	'1003'		=> '主控制: 向送經裝置的發出錯誤',
	'1004'		=> '主控制: 送經裝置來的結果值異常',
	'1005'		=> '主控制: 向送經裝置的超時錯誤',
	'1006'		=> '主控制: 向送經裝置的花紋切換異常',
	'1007'		=> '主控制: 向送經裝置的花紋設定錯誤',
	'1008'		=> '主控制: 向送經裝置的織口調整的通訊失敗',
	'1009'		=> '主控制: 向送經裝置的織口調整的通訊失敗',
	'1010'		=> '經紗準備狀態',
	'1011'		=> '主控制: 經紗準備狀態通訊失敗',
	'1050'		=> '主控製: 經紗張力大',
	'1051'		=> '主控制: 經紗張力小',
	'1100'		=> '主控制: 從送經裝置(上)來的緊急停車信號',
	'1101'		=> '主控制: 收到送經裝置(上)來的停車命令',
	'1102'		=> '主控制: 向送經裝置(上)的發出超時錯誤',
	'1103'		=> '主控制: 向送經裝置(上)的發出錯誤',
	'1104'		=> '主控制: 送經裝置(上)來的結果值異常',
	'1105'		=> '主控制: 向送經裝置(上)的超時錯誤',
	'1106'		=> '主控制: 向送經裝置(上)的花紋切換異常',
	'1107'		=> '主控制: 向送經裝置(上)的花紋設定錯誤',
	'1108'		=> '向送經裝置( 上 )的織口調整的通訊失敗',
	'1109'		=> '向送經裝置(上)的織口調整的通訊失敗',
	'1200'		=> '主控制: 從送經裝置(右)來的緊急停車信號',
	'1201'		=> '主控制: 收到送經裝置(右)來的停車命令',
	'1202'		=> '主控制: 向送經裝置(右)的發出超時錯誤',
	'1203'		=> '主控制: 向送經裝置(右)的發出錯誤',
	'1204'		=> '主控制: 送經裝置(右)來的結果值異常',
	'1205'		=> '主控制: 向送經裝置(右)的超時錯誤',
	'1206'		=> '主控制: 向送經裝置(右)的花紋切換異常',
	'1207'		=> '主控制: 向送經裝置(右)的花紋設定錯誤',
	'1208'		=> '向送經裝置(右)的織口調整的通訊失敗',
	'1209'		=> '向送經裝置(右)的織口調整的通訊失敗',
	'1300'		=> '主控制: 送經裝置(左)來的緊急停車信號',
	'1301'		=> '主控制: 收到送經裝置(左)來的停車命令',
	'1302'		=> '主控制: 向送經裝置(左)的發出超時錯誤',
	'1303'		=> '主控制: 向送經裝置(左)的發出錯誤',
	'1304'		=> '主控制: 送經裝置(左)來的結果值異常',
	'1305'		=> '主控制: 向送經裝置(左)的超時錯誤',
	'1306'		=> '主控制: 向送經裝置(左)的花紋切換異常',
	'1307'		=> '主控制: 向送經裝置(左)的花紋設定錯誤',
	'1308'		=> '向送經裝置(左)的織口調整的通訊失敗',
	'1309'		=> '向送經裝置(左)的織口調整的通訊失敗',
	'1400'		=> '主控制: 捲取裝置來的緊急停車信號',
	'1401'		=> '捲取: 伺服放大器異常檢出',
	'1402'		=> '捲取: 伺服放大器過速度異常',
	'1403'		=> '捲取: 伺服放大器的分析錯誤',
	'1404'		=> '捲取: 伺服放大器短時間過負載',
	'1405'		=> '捲取: 伺服馬達過熱( 軟體 )',
	'1406'		=> '捲取: 伺服放大器的速度放大器飽和',
	'1407'		=> '捲取: 伺服放大器過電流檢出( 軟體 )',
	'1408'		=> '捲取: 伺服放大器主回路繼電器異常',
	'1409'		=> '捲取: 伺服放大器分析部電纜斷線',
	'1410'		=> '捲取: 伺服放大器主回路AC電壓偏低',
	'1411'		=> '捲取: 伺服放大器過電壓檢出',
	'1412'		=> '捲取: 伺服放大器的IPM異常檢出',
	'1413'		=> '捲取滾筒正轉中',
	'1414'		=> '捲取滾筒逆轉中',
	'1415'		=> '捲取: 伺服計數器溢出',
	'1416'		=> '捲取: 伺服放大器回歸異常',
	'1417'		=> '捲取: 伺服放大器緊急停車解除中',
	'1418'		=> '卷取: 編碼器訊號出錯',
	'1419'		=> '卷取: 通訊,超時',
	'1420'		=> '卷取: 通訊,伺服放大器接收異常',
	'1421'		=> '卷取: 通訊,伺服放大器應答異常',
	'1422'		=> '主控制: 向捲取裝置的織口調整的通訊失敗',
	'1423'		=> '卷取: 方向信號的通訊失敗',
	'1450'		=> '主控制: 捲取裝置(BW)來的停車信號',
	'1470'		=> '主控制: 捲取裝置來的緊急停車信號',
	'1471'		=> '主控制: 收到捲取裝置來的停車命令',
	'1472'		=> '主控制: 向捲取裝置的發出超時錯誤',
	'1473'		=> '主控制: 向捲取裝置的發出錯誤',
	'1474'		=> '主控制: 捲取裝置來的結果值異常',
	'1475'		=> '主控制: 向捲取裝置的超時錯誤',
	'1476'		=> '主控制: 向捲取裝置的花紋切換異常',
	'1477'		=> '主控制: 向捲取裝置的花紋設定錯誤',
	'1478'		=> '主控制: 向捲取裝置的織口調整的通訊失敗',
	'1479'		=> '主控制: 向捲取裝置的織口調整的通訊失敗',
	'1480'		=> '主控制: 查出送經的駕駛狀態異常',
	'1490'		=> '主控制: 向送經裝置的通訊失敗(option.set)',
	'1491'		=> '主控制: 向送經(左)裝置的通訊失敗(option.set)',
	'1492'		=> '主控制: 向送經(右)裝置的通訊失敗(option.set)',
	'1493'		=> '主控制: 向送經(上)裝置的通訊失敗(option.set)',
	'1494'		=> '主控制: 向捲取裝置的通訊失敗(option.set)',
	'1495'		=> '送經: 復位',
	'1496'		=> '送經(左): 復位',
	'1497'		=> '送經(右): 復位',
	'1498'		=> '送經(上): 復位',
	'1499'		=> '捲取: 復位',
	'1500'		=> 'TAPO: 因在處理中,機台不能操作',
	'1506'		=> 'TAPO:捲取失敗',
	'1600'		=> 'APC: 氣壓原太低',
	'1601'		=> 'APC: 主噴口1壓力的上限',
	'1602'		=> 'APC: 主噴口1壓力的下限',
	'1603'		=> 'APC: 主噴口2壓力的上限',
	'1604'		=> 'APC: 主噴口2壓力的下限',
	'1605'		=> 'APC: 主噴口3壓力的上限',
	'1606'		=> 'APC: 主噴口3壓力的下限',
	'1607'		=> 'APC: 主噴口4壓力的上限',
	'1608'		=> 'APC: 主噴口4壓力的下限',
	'1609'		=> 'APC: 主噴口5壓力的上限',
	'1610'		=> 'APC: 主噴口5壓力的下限',
	'1611'		=> 'APC: 主噴口6壓力的上限',
	'1612'		=> 'APC: 主噴口6壓力的下限',
	'1613'		=> 'APC: 副噴口壓力的上限',
	'1614'		=> 'APC: 副噴口壓力的下限',
	'1615'		=> 'APC: 末端副噴壓力的上限',
	'1616'		=> 'APC: 末端副噴壓力的下限',
	'1650'		=> 'APC: Tw超出設定範圍( 第1梭/ 色 )',
	'1651'		=> 'APC: Tw超出設定範圍( 第2梭/ 色 )',
	'1652'		=> 'APC: Tw超出設定範圍( 第3梭/ 色 )',
	'1653'		=> 'APC: Tw超出設定範圍( 第4梭/ 色 )',
	'1654'		=> 'APC: Tw超出設定範圍( 第5梭/ 色 )',
	'1655'		=> 'APC: Tw超出設定範圍( 第6梭/ 色 )',
	'1670'		=> 'ITC: 壓力傳感器異常檢出',
	'1700'		=> '主控制: 輸入SCI裝置來的緊急停車信號',
	'1701'		=> '主控制: 收到SCI裝置來的停車命令',
	'1702'		=> '主控制: 與SCI裝置通訊失敗',
	'1703'		=> 'SCI: 過熱保護',
	'1704'		=> 'SCI: 過電流保護',
	'1705'		=> 'SCI: 過電壓保護',
	'1706'		=> 'SCI: 電壓不足保護',
	'1707'		=> 'SCI: 主馬達回轉數異常',
	'1708'		=> 'SCI: 主馬達回轉數異常',
	'1709'		=> 'SCI: 收到緊急停車信號',
	'1710'		=> 'SCI: IPM異常',
	'1711'		=> 'SCI: 程序另寫可能狀態',
	'1712'		=> 'SCI: 程序的寫入失敗',
	'1800'		=> '電子多臂: 潤滑油量異常',
	'1801'		=> '電子多臂: 近接信號異常',
	'1802'		=> '電子多臂: 翻轉禁止( 正轉←逆轉 )',
	'1803'		=> '電子多臂: 翻轉禁止( 逆轉←正轉 )',
	'1804'		=> '電子多臂: 翻轉禁止  寸動( 正轉←逆轉 )',
	'1805'		=> '電子多臂: 翻轉禁止  寸動( 逆轉←正轉 )',
	'1806'		=> '電子多臂: 電磁線圈NO1的斷線',
	'1807'		=> '電子多臂: 電磁線圈NO2的斷線',
	'1808'		=> '電子多臂: 電磁線圈NO3的斷線',
	'1809'		=> '電子多臂: 電磁線圈NO4的斷線',
	'1810'		=> '電子多臂: 電磁線圈NO5的斷線',
	'1811'		=> '電子多臂: 電磁線圈NO6的斷線',
	'1812'		=> '電子多臂: 電磁線圈NO7的斷線',
	'1813'		=> '電子多臂: 電磁線圈NO8的斷線',
	'1814'		=> '電子多臂: 電磁線圈NO9的斷線',
	'1815'		=> '電子多臂: 電磁線圈NO10的斷線',
	'1816'		=> '電子多臂: 電磁線圈NO11的斷線',
	'1817'		=> '電子多臂: 電磁線圈NO12的斷線',
	'1818'		=> '電子多臂: 電磁線圈NO13的斷線',
	'1819'		=> '電子多臂: 電磁線圈NO14的斷線',
	'1820'		=> '電子多臂: 電磁線圈NO15的斷線',
	'1821'		=> '電子多臂: 電磁線圈NO16的斷線',
	'1822'		=> '電子多臂: 電磁線圈NO17的斷線',
	'1823'		=> '電子多臂: 電磁線圈NO18的斷線',
	'1824'		=> '電子多臂: 電磁線圈NO19的斷線',
	'1825'		=> '電子多臂: 電磁線圈NO20的斷線',
	'2000'		=> '主控制: 打絞,圖案異常',
	'2001'		=> '主控制: 打絞( 右 )報警',
	'2002'		=> '主控制: 打絞( 左 )報警',
	'2003'		=> '主控制: 打絞( 右 )起源查出失敗',
	'2004'		=> '主控制: 打絞( 左 )起源查出失敗',
	'2005'		=> '主控制: 打絞( 右 )伺服放大器過電流檢出',
	'2006'		=> '主控制: 打絞( 左 )伺服放大器過電流檢出',
	'2100'		=> '遙控: 不能起動',
	'2102'		=> '主控制: 圖案異常',
	'2103'		=> '主控制: 圖案異常( 色 )',
	'2104'		=> '主控制: 圖案異常( 密度 )',
	'2105'		=> '主控制: 圖案異常( 選擇訊號 )',
	'2106'		=> '主控制: 圖案異常( 開口 )',
	'2107'		=> '主控製: 花樣第一緯初始化',
	'2108'		=> '主控製: 時鐘異常',
	'2109'		=> '機台的顯示時間不准',
	'2110'		=> '主控制: 密度異常',
	'2170'		=> '監視中止',
	'2200'		=> '由于尾紗自動處理中,機台不能動作',
	'2201'		=> '殘紗排出失敗  繞線筒1',
	'2202'		=> '殘紗排出失敗  繞線筒2',
	'2203'		=> '殘紗排出失敗  繞線筒3',
	'2204'		=> '殘紗排出失敗  繞線筒4',
	'2205'		=> '殘紗排出失敗  繞線筒5',
	'2206'		=> '殘紗排出失敗  繞線筒6',
	'2207'		=> '殘紗排出失敗  繞線筒7',
	'2208'		=> '殘紗排出失敗  繞線筒8',
	'2210'		=> '殘紗狀態  繞線筒1',
	'2211'		=> '殘紗狀態  繞線筒2',
	'2212'		=> '殘紗狀態  繞線筒3',
	'2213'		=> '殘紗狀態  繞線筒4',
	'2214'		=> '殘紗狀態  繞線筒5',
	'2215'		=> '殘紗狀態  繞線筒6',
	'2216'		=> '殘紗狀態  繞線筒7',
	'2217'		=> '殘紗狀態  繞線筒8',
	'2218'		=> '尾紗傳感器1信號檢出',
	'2219'		=> '尾紗傳感器2信號檢出',
	'2220'		=> '尾紗傳感器3信號檢出',
	'2221'		=> '尾紗傳感器4信號檢出',
	'2222'		=> '尾紗傳感器1異常(斷線)',
	'2223'		=> '尾紗傳感器2異常(斷線)',
	'2224'		=> '尾紗傳感器3異常(斷線)',
	'2225'		=> '尾紗傳感器4異常(斷線)',
	'2226'		=> '尾紗傳感器信號停止',
	'2227'		=> '沒有繞線筒傳感器信號',
	'2228'		=> 'APC壓力初始化中',
	'2229'		=> '請用手動處理尾紗',
	'2230'		=> '請確認尾紗',
	'2231'		=> '請更換空筒管',
	'2232'		=> '繞線筒傳感器,尾紗傳感器  無效',
	'2233'		=> 'APC:壓力初始化失敗',
	'2234'		=> '尾紗傳感器5信號檢出',
	'2235'		=> '尾紗傳感器6信號檢出',
	'2236'		=> '尾紗傳感器5異常(斷線)',
	'2237'		=> '尾紗傳感器6異常(斷線)',
	'2300'		=> '主控制: 與開口裝置間的通訊失敗',
	'2301'		=> '主控制: 從開口裝置輸入緊急停止訊號',
	'2302'		=> '主控制: 接收到主軸原點對合未結束的訊息',
	'2303'		=> '主控制: 與開口裝置間的狀態通訊失敗',
	'2304'		=> '主控制: 與開口裝置間的整平解除通訊失敗',
	'2305'		=> '主控制: 與開口裝置間的紗框原點對合通訊失敗',
	'2306'		=> '主控制: 與開口裝置間的整平通訊失敗',
	'2307'		=> '尚未實施開口裝置的同步對合,所以不可進行PF動作',
	'2308'		=> '尚未實施開口裝置的紗框原點對合,所以不可進行整平',
	'2309'		=> '主控制: 從開口裝置接收到停止命令',
	'2310'		=> '自動整平中的微動禁止區域',
	'2311'		=> '主控制: 未檢測到0度,所以不可動作',
	'2312'		=> '正在確認花樣',
	'2400'		=> '主控製: 來自開口裝置的請求應答訊號異常',
	'2401'		=> '主控制: 無來自提花裝置的要求應答訊號',
	'2402'		=> '主控制: 提花裝置與圖案在確認中',
	'2403'		=> '主控制: 來自提花裝置的顏色選擇訊號異常',
	'2404'		=> '主控制: 圖案異常',
	'2405'		=> '主控制: 從提花裝置輸入圖案變更訊號',
	'2406'		=> '主控制: 從提花裝置輸入停止訊號',
	'2407'		=> '主控制: 從提花裝置輸入正轉禁止訊號',
	'2408'		=> '主控制: 從提花裝置輸入反轉禁止訊號',
	'2410'		=> '主控製: 毛圈運動裝置報警',
	'2411'		=> '主控製: 毛圈數據超出范圍',
	'2417'		=> '主控制: 來自提花裝置的選擇訊號異常',
	'2418'		=> '主控製: 張力訊號異常( 毛圈紗 )',
	'2419'		=> '主控製: 張力訊號異常( 地紗 )',
	'2423'		=> '主控製: 來自開口裝置的毛邊輸入訊號',
	'2424'		=> '卷布輥落卷( 毛邊 )',
	'2425'		=> '卷布輥落卷( 折布 )',
	'2426'		=> '主控製: 花樣第一緯初始化',
	'2452'		=> '主控製: 與毛圈送經裝置的通訊失敗',
	'2470'		=> '主控製: TUCKER傳送帶 斷裂',
	'4500'		=> '單獨織邊(右): 起源查出失敗',
	'4501'		=> '單獨織邊(右): 原點未檢測',
	'4505'		=> '單獨織邊(右): 報警信號輸入',
	'4506'		=> '單獨織邊(右): 脈衝輸出異常',
	'4510'		=> '單獨織邊(左): 起源查出失敗',
	'4511'		=> '單獨織邊(左): 原點未檢測',
	'4515'		=> '單獨織邊(左): 報警信號輸入',
	'4516'		=> '單獨織邊(左): 脈衝輸出異常',

	######## End of Data ########

	'OTHER_STOP'	=> '其他停機'	);
}

###################################################################################################

sub load_stop_cause_str_lwt710
{
  return (

	'0000'		=> 'WARP STOP',
	'0001'		=> 'WASTE-SELVAGE STOP (FRONT)',
	'0002'		=> 'WASTE-SELVAGE STOP (REAR)',
	'0003'		=> 'FULL-LENO SELVAGE STOP (RIGHT-HAND)',
	'0004'		=> 'FULL-LENO SELVAGE STOP (LEFT-HAND)',
	'0005'		=> 'WEFT STOP (COLOR 1)',
	'0006'		=> 'WEFT STOP (COLOR 2)',
	'0007'		=> 'WEFT STOP (COLOR 3)',
	'0008'		=> 'WEFT STOP (COLOR 4)',
	'0009'		=> 'WEFT SUPPLY STOP (COLOR 1)',
	'0010'		=> 'WEFT SUPPLY STOP (COLOR 2)',
	'0011'		=> 'WEFT SUPPLY STOP (COLOR 3)',
	'0012'		=> 'WEFT SUPPLY STOP (COLOR 4)',
	'0013'		=> 'CLOTH BEAM TO BE DOFFED',
	'0026'		=> 'CLOTH BEAM DOFFING SIGNALLED',
	'0014'		=> '[STOP] SWITCH PRESSED',
	'0015'		=> 'EMERGENCY STOP BUTTON PRESSED',
	'0110'		=> 'FEELER IS OFF SETTING',
	'0126'		=> 'FEELER SENSOR OFF',
	'2100'		=> 'REMOTE CONTROL LOCK',
	'2101'		=> 'REMOTE CONTROL STOP',
	'2150'		=> 'DECLARE(M/C TROUBLE)',
	'2151'		=> 'DECLARE(MENDING)',
	'2153'		=> 'DECLARE(WARP OUT)',
	'2154'		=> 'DECLARE(CLOTH DOFFING)',
	'2155'		=> 'DECLARE(FOREMAN CALL ON)',

	'0023'		=> 'WASTE-SELVAGE ROLLER TANGLED',
	'0024'		=> 'LIGHT BARRIER INTERRUPTED (SAFETY DEVICE ON)',
	'0102'		=> 'OILING FAILED',
	'0105'		=> 'HANDLE COVER NOT INSTALLED',
	'0116'		=> 'OILING SENSOR STOP(SHEDDING MACHINE)',
	'0117'		=> 'OILING NOW( VALVE RESTORING )',
	'0118'		=> 'OILING FAILED( PRESSURE IS LOW )',
	'0119'		=> 'OILING FAILED( PRESSURE IS HIGH )',
	'0122'		=> 'ABNORMAL OIL PUMP(SHEDDING MACHINE)',
	'0137'		=> 'CLOSE WINDOW COVER',
	'0138'		=> 'WINDOW COVER SENSOR OFF',
	'0139'		=> 'WEFT BREAK STOP (COLOR 1)',
	'0140'		=> 'WEFT BREAK STOP (COLOR 2)',
	'0141'		=> 'WEFT BREAK STOP (COLOR 3)',
	'0142'		=> 'WEFT BREAK STOP (COLOR 4)',
	'0207'		=> 'BRAKE VOLTAGE FAILURE',
	'0210'		=> 'MAIN MOTOR OVERLOAD',
	'0211'		=> '140V[DCPS2] VDC FAILURE',
	'0212'		=> '24V[DCPS2] FAILURE',
	'0213'		=> '24V[DCPS4] FAILURE',
	'0214'		=> '24V[DCPS2] FAILURE',
	'0215'		=> '48V[DCPS2] FAILURE',
	'0216'		=> '12V[DCPS2] FAILURE',
	'0217'		=> 'P15V[DCPS10] FAILURE',
	'0218'		=> 'M15V[DCPS10] FAILURE',
	'0219'		=> '12V[DCPS3] FAILURE',
	'0220'		=> '5V FAILURE',
	'0221'		=> 'WARP DETECTOR DISCONNECTED',
	'0222'		=> 'MAIN MOTOR OVERHEAT',
	'0223'		=> 'ENCODER, Z-PHASE ERROR',
	'0224'		=> 'ENCODER, A- OR B-PHASE ERROR',
	'0225'		=> 'MAIN CONTROL:LOW BATTERY VOLTAGE',
	'0226'		=> 'BLOWER MOTOR OVERLOAD',
	'0227'		=> 'BLOWER MOTOR OVERLOAD',
	'0228'		=> 'SAFETY DEVICE FAILURE',
	'0229'		=> 'HEAT CUTTER TROUBLE',
	'0230'		=> 'BRAKE VOLTAGE FAIL (DRIVE)',
	'0280'		=> 'CPU BOARD FAILURE',
	'0281'		=> 'ETHERNET CH0 ERROR',
	'0282'		=> 'ETHERNET CH1 ERROR',
	'0300'		=> 'INVERTER FAILURE OR INCHING OVERLOAD',
	'0301'		=> 'LACK OF BRAKE TORQUE',
	'0302'		=> 'WF1 FAILURE',
	'0303'		=> 'WF2 FAILURE',
	'0304'		=> 'NO INPUT FROM ENCODER Z-PHASE (IN OPERATION)',
	'0305'		=> 'REVERSE-REV. PULSE FROM ENCODER (IN OPERATION)',
	'0306'		=> 'ENCODER FWD-REV. PULSE COUNT ERROR (IN OPERATION)',
	'0307'		=> 'WINDING SENSOR FAILURE',
	'0308'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 1)',
	'0309'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 2)',
	'0310'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 3)',
	'0311'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 4)',
	'0312'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 5)',
	'0313'		=> 'WINDING SENSOR SIGNALS MORE THAN NO.OF ACTUAL TURNS (COLOR 6)',
	'0314'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 1)',
	'0315'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 2)',
	'0316'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 3)',
	'0317'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 4)',
	'0318'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 5)',
	'0319'		=> 'WINDING SENSOR SIGNALS LESS THAN NO.OF ACTUAL TURNS (COLOR 6)',
	'0320'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 1)',
	'0321'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 2)',
	'0322'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 3)',
	'0323'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 4)',
	'0324'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 5)',
	'0325'		=> 'ABS: FAILED TO DETECT ORIGIN (COLOR 6)',
	'0326'		=> 'ABS: CROSSING TIME ERROR (COLOR 1)',
	'0327'		=> 'ABS: CROSSING TIME ERROR (COLOR 2)',
	'0328'		=> 'ABS: CROSSING TIME ERROR (COLOR 3)',
	'0329'		=> 'ABS: CROSSING TIME ERROR (COLOR 4)',
	'0330'		=> 'ABS: CROSSING TIME ERROR (COLOR 5)',
	'0331'		=> 'SPINDLE: PULSE OVER',
	'0332'		=> 'ABS: ALARM GENERATED (COLOR 1)',
	'0333'		=> 'ABS: ALARM GENERATED (COLOR 2)',
	'0334'		=> 'ABS: ALARM GENERATED (COLOR 3)',
	'0335'		=> 'ABS: ALARM GENERATED (COLOR 4)',
	'0336'		=> 'ABS: ALARM GENERATED (COLOR 5)',
	'0403'		=> 'MAIN CONTROL: DATA COMMUNICATION FAILURE (SOMIC ch0)',
	'0404'		=> 'MAIN CONTROL: DATA COMMUNICATION FAILURE (SOMIC ch1)',
	'1000'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM LET-OFF',
	'1001'		=> 'MAIN CONTROL: STOP SIGNAL FROM LET-OFF',
	'1002'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH LET-OFF',
	'1003'		=> 'MAIN CONTROL: SEND ERROR, WITH LET-OFF',
	'1004'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM LET-OFF',
	'1005'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH LET-OFF',
	'1006'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR PATTERN CHANGE',
	'1007'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR PATTERN SETTING',
	'1008'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR STOP MARK SIGNAL',
	'1009'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR FELL-FWD SIGNAL',
	'1010'		=> 'BEAM PREPARE MODE',
	'1011'		=> 'MAIN CONTROL: FAILURE TO LET-OFF FOR BEAM PREPARE MODE',
	'1050'		=> 'MAIN CONTROL:TOO HIGH WARP TENSION',
	'1051'		=> 'MAIN CONTROL:TOO LOW WARP TENSION',
	'1100'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM UPPER LET-OFF',
	'1101'		=> 'MAIN CONTROL: STOP SIGNAL FROM UPPER LET-OFF',
	'1102'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH UPPER LET-OFF',
	'1103'		=> 'MAIN CONTROL: SEND ERROR, WITH UPPER LET-OFF',
	'1104'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM UPPER LET-OFF',
	'1105'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH UPPER LET-OFF',
	'1106'		=> 'MAIN CONTROL: FAILURE TO UPPER LET-OFF FOR PATTERN CHANGE',
	'1107'		=> 'MAIN CONTROL: FAILURE TO UPPER LET-OFF FOR PATTERN SETTING',
	'1108'		=> 'MAIN CONTROL: FAILURE TO UPPER LET-OFF FOR STOP MARK SIGNAL',
	'1109'		=> 'MAIN CONTROL: FAILURE TO UPPER LET-OFF FOR FELL-FWD SIGNAL',
	'1200'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM RH_LET-OFF',
	'1201'		=> 'MAIN CONTROL: STOP SIGNAL FROM RH_LET-OFF',
	'1202'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH RH LET-OFF',
	'1203'		=> 'MAIN CONTROL: SEND ERROR, WITH RH LET-OFF',
	'1204'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM RH LET-OFF',
	'1205'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH RH LET-OFF',
	'1206'		=> 'MAIN CONTROL: FAILURE TO RH LET-OFF FOR PATTERN CHANGE',
	'1207'		=> 'MAIN CONTROL: FAILURE TO RH LET-OFF FOR PATTERN SETTING',
	'1208'		=> 'MAIN CONTROL: FAILURE TO RH LET-OFF FOR STOP MARK SIGNAL',
	'1209'		=> 'MAIN CONTROL: FAILURE TO RH LET-OFF FOR FELL-FWD SIGNAL',
	'1300'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM LH_LET-OFF',
	'1301'		=> 'MAIN CONTROL: STOP SIGNAL FROM LH_LET-OFF',
	'1302'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH LH LET-OFF',
	'1303'		=> 'MAIN CONTROL: SEND ERROR, WITH LH LET-OFF',
	'1304'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM LH LET-OFF',
	'1305'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH LH LET-OFF',
	'1306'		=> 'MAIN CONTROL: FAILURE TO LH LET-OFF FOR PATTERN CHANGE',
	'1307'		=> 'MAIN CONTROL: FAILURE TO LH LET-OFF FOR PATTERN SETTING',
	'1308'		=> 'MAIN CONTROL: FAILURE TO LH LET-OFF FOR STOP MARK SIGNAL',
	'1309'		=> 'MAIN CONTROL: FAILURE TO LH LET-OFF FOR FELL-FWD SIGNAL',
	'1400'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM TAKE-UP',
	'1401'		=> 'TAKE-UP:SERVO AMPLIFIER ERROR',
	'1402'		=> 'TAKE-UP:SERVO AMPLIFIER OVERSHOOT',
	'1403'		=> 'TAKE-UP:RESOLVER FEEDBACK ERROR',
	'1404'		=> 'TAKE-UP:SERVO AMP. TENTATIVELY OVERLOADED',
	'1405'		=> 'TAKE-UP:SERVOMOTOR OVERHEAT (SOFTWARE-DETECTED)',
	'1406'		=> 'TAKE-UP:SERVO AMP., SPEED CONTROL AMP. SATURATED',
	'1407'		=> 'TAKE-UP:SERVO AMP. OVERCURRENT (SOFTWARE-DETECTED)',
	'1408'		=> 'TAKE-UP:SERVO AMP., MAIN CIRCUIT CONTACTOR ERROR',
	'1409'		=> 'TAKE-UP:RESOLVER CABLE BROKEN',
	'1410'		=> 'TAKE-UP:DROPPED MAIN AC POWER SUPPLY VOLTAGE TO SERVO AMP.',
	'1411'		=> 'TAKE-UP:OVERVOLTAGE SUPPLIED TO SERVO AMP.',
	'1412'		=> 'TAKE-UP:SERVO AMP., IPM ERROR',
	'1413'		=> 'SURFACE ROLLER IN FORWARD ROTATION',
	'1414'		=> 'SURFACE ROLLER IN REVERSE ROTATION',
	'1415'		=> 'TAKE-UP:SERVOCOUNTER OVERFLOW',
	'1416'		=> 'TAKE-UP:SERVO AMP. RELEASE ERROR',
	'1417'		=> 'TAKE-UP:SERVO AMP. EMERGENCY-STOP BEING RELEASED',
	'1418'		=> 'TAKE-UP:ABNORMAL SIGNAL FROM ENCORDER',
	'1419'		=> 'TAKE-UP:COMMUNICATION, TIME-OUT ERROR',
	'1420'		=> 'TAKE-UP:COMMUNICATION, SERVO_AMP RECEIVE ERROR',
	'1421'		=> 'TAKE-UP:COMMUNICATION, SERVO_AMP RESPONSE ERROR',
	'1422'		=> 'MAIN CONTROL:FAILURE TO TAKE-UP FOR FELL-FWD SIGNAL',
	'1423'		=> 'TAKE-UP:COMMUNICATION, DIRECTION SIGNAL FAILURE',
	'1450'		=> 'MAIN CONTROL:STOP SIGNAL FROM TAKE-UP(BW)',
	'1470'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM TAKEUP',
	'1471'		=> 'MAIN CONTROL: STOP SIGNAL FROM TAKEUP',
	'1472'		=> 'MAIN CONTROL: SEND TIME-OUT, WITH TAKEUP',
	'1473'		=> 'MAIN CONTROL: SEND ERROR, WITH TAKEUP',
	'1474'		=> 'MAIN CONTROL: NEGATIVE RESPONSE FROM TAKEUP',
	'1475'		=> 'MAIN CONTROL: TIME-OUT ERROR, WITH TAKEUP',
	'1476'		=> 'MAIN CONTROL: FAILURE TO TAKEUP FOR PATTERN CHANGE',
	'1477'		=> 'MAIN CONTROL: FAILURE TO TAKEUP FOR PATTERN SETTING',
	'1478'		=> 'MAIN CONTROL: FAILURE TO TAKEUP FOR STOP MARK SIGNAL',
	'1479'		=> 'MAIN CONTROL: FAILURE TO TAKEUP FOR FELL-FWD SIGNAL',
	'1480'		=> 'MAIN CONTROL: FAILURE TO LET-OFF STATUS IN OPERATION',
	'1490'		=> 'MAIN CONTROL: FAILURE TO LETOFF (option.set)',
	'1491'		=> 'MAIN CONTROL: FAILURE TO LH LETOFF (option.set)',
	'1492'		=> 'MAIN CONTROL: FAILURE TO RH LETOFF (option.set)',
	'1493'		=> 'MAIN CONTROL: FAILURE TO UPPER LETOFF (option.set)',
	'1494'		=> 'MAIN CONTROL: FAILURE TO TAKEUP (option.set)',
	'1495'		=> 'LETOFF: RESET',
	'1496'		=> 'LETOFF(L): RESET',
	'1497'		=> 'LETOFF(R): RESET',
	'1498'		=> 'LETOFF(UPPER): RESET',
	'1499'		=> 'TAKEUP: RESET',
	'1700'		=> 'MAIN CONTROL: EMERGENCY STOP SIGNAL FROM SC INVERTER',
	'1701'		=> 'MAIN CONTROL: STOP SIGNAL FROM SC INVERTER',
	'1702'		=> 'MAIN CONTROL: COMMUNICATIONS ERROR, WITH SC INVERTER',
	'1703'		=> 'SC INVERTER:OVERHEAT',
	'1704'		=> 'SC INVERTER:OVERCURRENT',
	'1705'		=> 'SC INVERTER:OVERVOLTAGE',
	'1706'		=> 'SC INVERTER:LOW VOLTAGE',
	'1707'		=> 'SC INVERTER:MAIN MOTOR REVOLUTION ERROR',
	'1708'		=> 'SC INVERTER:MAIN MOTOR REVOLUTION ERROR',
	'1709'		=> 'SC INVERTER:EMERGENCY STOP SIGNAL FROM MAIN CONTROL',
	'1710'		=> 'SC INVERTER:IPM ERROR',
	'1711'		=> 'SC INVERTER:PROGRAM REWRITABLE STATE',
	'1712'		=> 'SC INVERTER:FAILURE OF PROGRAM WRITING',
	'1800'		=> 'DOBBY: ABNORMAL OIL PUMP',
	'1801'		=> 'DOBBY: ABNORMAL SIGNALLING FM PROXIMITY SWITCHES',
	'1802'		=> 'DOBBY: INVERSION PROHIBITED FM FWD TO REVERSE',
	'1803'		=> 'DOBBY: INVERSION PROHIBITED FM REVERSE TO FWD',
	'1804'		=> 'DOBBY: INCHING IN UNINVERTIBLE-ANGLE RANGE (FM FWD TO REVERSE)',
	'1805'		=> 'DOBBY: INCHING IN UNINVERTIBLE-ANGLE RANGE (FM REVERSE TO FWD)',
	'1806'		=> 'DOBBY: NO.01 SOLENOID BREAK',
	'1807'		=> 'DOBBY: NO.02 SOLENOID BREAK',
	'1808'		=> 'DOBBY: NO.03 SOLENOID BREAK',
	'1809'		=> 'DOBBY: NO.04 SOLENOID BREAK',
	'1810'		=> 'DOBBY: NO.05 SOLENOID BREAK',
	'1811'		=> 'DOBBY: NO.06 SOLENOID BREAK',
	'1812'		=> 'DOBBY: NO.07 SOLENOID BREAK',
	'1813'		=> 'DOBBY: NO.08 SOLENOID BREAK',
	'1814'		=> 'DOBBY: NO.09 SOLENOID BREAK',
	'1815'		=> 'DOBBY: NO.10 SOLENOID BREAK',
	'1816'		=> 'DOBBY: NO.11 SOLENOID BREAK',
	'1817'		=> 'DOBBY: NO.12 SOLENOID BREAK',
	'1818'		=> 'DOBBY: NO.13 SOLENOID BREAK',
	'1819'		=> 'DOBBY: NO.14 SOLENOID BREAK',
	'1820'		=> 'DOBBY: NO.15 SOLENOID BREAK',
	'1821'		=> 'DOBBY: NO.16 SOLENOID BREAK',
	'1822'		=> 'DOBBY: NO.17 SOLENOID BREAK',
	'1823'		=> 'DOBBY: NO.18 SOLENOID BREAK',
	'1824'		=> 'DOBBY: NO.19 SOLENOID BREAK',
	'1825'		=> 'DOBBY: NO.20 SOLENOID BREAK',
	'2000'		=> 'MAIN CONTROL:LENO, ABNORMAL DATA',
	'2001'		=> 'MAIN CONTROL:LENO(R) ALARM SIGNAL INPUT',
	'2002'		=> 'MAIN CONTROL:LENO(L) ALARM SIGNAL INPUT',
	'2003'		=> 'MAIN CONTROL:LENO(R) FAILED TO DETECT ORIGIN',
	'2004'		=> 'MAIN CONTROL:LENO(L) FAILED TO DETECT ORIGIN',
	'2005'		=> 'MAIN CONTROL:LENO(R) SERVO AMP. OVERCURRENT',
	'2006'		=> 'MAIN CONTROL:LENO(L) SERVO AMP. OVERCURRENT',
	'2102'		=> 'MAIN CONTROL:ABNORMAL PATTERN',
	'2103'		=> 'MAIN CONTROL:ABNORMAL COLOR',
	'2104'		=> 'MAIN CONTROL:ABNORMAL DENSITY',
	'2105'		=> 'MAIN CONTROL:ABNORMAL PILE DATA',
	'2106'		=> 'MAIN CONTROL:ABNORMAL SHEDDING PATTERN',
	'2112'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL',
	'2113'		=> 'YARN TAIL END SENSOR IS ABNORMAL (WIRE BREAK)',
	'2114'		=> 'OPERATE YARN TAIL HANDLING MANUALLY',
	'2115'		=> 'TAIL END SENSOR ARE OFF',
	'2116'		=> 'YARN TAIL END SENSOR: WIRE BREAK(COLOR 1)',
	'2117'		=> 'YARN TAIL END SENSOR: WIRE BREAK(COLOR 2)',
	'2118'		=> 'YARN TAIL END SENSOR: WIRE BREAK(COLOR 3)',
	'2119'		=> 'YARN TAIL END SENSOR: WIRE BREAK(COLOR 4)',
	'2120'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL(COLOR 1)',
	'2121'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL(COLOR 2)',
	'2122'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL(COLOR 3)',
	'2123'		=> 'YARN TAIL END SENSOR DETECTS SIGNAL(COLOR 4)',
	'2170'		=> 'MONITORING STOP NOW',

	######## End of Data ########

	'OTHER_STOP'	=> '其他停機'	);
}

###################################################################################################
1;
